export default {
  overall: {
    averageWordsPerReview: 131.03076923076924,
    reviewCount: 130,
  },
  gradeDistribution: {
    stats: [
      {
        grade: "A+",
        reviewCount: 5,
      },
      {
        grade: "A",
        reviewCount: 4,
      },
      {
        grade: "A-",
        reviewCount: 4,
      },
      {
        grade: "B+",
        reviewCount: 8,
      },
      {
        grade: "B",
        reviewCount: 9,
      },
      {
        grade: "B-",
        reviewCount: 11,
      },
      {
        grade: "C+",
        reviewCount: 28,
      },
      {
        grade: "C",
        reviewCount: 15,
      },
      {
        grade: "C-",
        reviewCount: 4,
      },
      {
        grade: "D+",
        reviewCount: 28,
      },
      {
        grade: "D",
        reviewCount: 6,
      },
      {
        grade: "F",
        reviewCount: 8,
      },
    ],
  },
  decade: {
    stats: [
      {
        decade: "1920s",
        averageGradeValue: 2.391818181818181,
      },
      {
        decade: "1930s",
        averageGradeValue: 2.8449999999999993,
      },
      {
        decade: "1940s",
        averageGradeValue: 2.7216666666666662,
      },
      {
        decade: "1950s",
        averageGradeValue: 3.4659999999999997,
      },
      {
        decade: "1960s",
        averageGradeValue: 2.9433333333333334,
      },
      {
        decade: "1970s",
        averageGradeValue: 3.1809090909090902,
      },
      {
        decade: "1980s",
        averageGradeValue: 3.7849999999999997,
      },
      {
        decade: "1990s",
        averageGradeValue: 2.7142857142857144,
      },
      {
        decade: "2000s",
        averageGradeValue: 3.4416666666666664,
      },
      {
        decade: "2010s",
        averageGradeValue: 3.618965517241379,
      },
      {
        decade: "2020s",
        averageGradeValue: 2.2475,
      },
    ],
  },
  directors: {
    highestRated: [
      {
        fullName: "Anthony Russo",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.886666666666667,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Joe Russo",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.886666666666667,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Terence Fisher",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 4.835,
        reviews: [
          {
            sequence: 872,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 5,
            title: "The Curse of Frankenstein",
            year: 1957,
            slug: "the-curse-of-frankenstein-1957",
          },
          {
            sequence: 936,
            prettyDate: "Tue Dec 8, 2020",
            gradeValue: 4.67,
            title: "Horror of Dracula",
            year: 1958,
            slug: "horror-of-dracula-1958",
          },
        ],
      },
      {
        fullName: "Lucio Fulci",
        slug: "lucio-fulci",
        reviewCount: 5,
        averageGradeValue: 3.6,
        reviews: [
          {
            sequence: 873,
            prettyDate: "Mon Sep 21, 2020",
            gradeValue: 3.33,
            title: "Massacre Time",
            year: 1966,
            slug: "the-brute-and-the-beast-1966",
          },
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            gradeValue: 4,
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 3.67,
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            gradeValue: 3.33,
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            gradeValue: 3.67,
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
        ],
      },
      {
        fullName: "Tod Browning",
        slug: "tod-browning",
        reviewCount: 2,
        averageGradeValue: 3.5,
        reviews: [
          {
            sequence: 854,
            prettyDate: "Mon Aug 17, 2020",
            gradeValue: 2.33,
            title: "The Thirteenth Chair",
            year: 1929,
            slug: "the-thirteenth-chair-1929",
          },
          {
            sequence: 880,
            prettyDate: "Sun Oct 4, 2020",
            gradeValue: 4.67,
            title: "Dracula",
            year: 1931,
            slug: "dracula-1931",
          },
        ],
      },
      {
        fullName: "Howard Hawks",
        slug: "howard-hawks",
        reviewCount: 2,
        averageGradeValue: 3.5,
        reviews: [
          {
            sequence: 869,
            prettyDate: "Sun Sep 13, 2020",
            gradeValue: 3.67,
            title: "The Dawn Patrol",
            year: 1930,
            slug: "the-dawn-patrol-1930",
          },
          {
            sequence: 919,
            prettyDate: "Wed Nov 18, 2020",
            gradeValue: 3.33,
            title: "The Criminal Code",
            year: 1930,
            slug: "the-criminal-code-1930",
          },
        ],
      },
      {
        fullName: "Ingmar Bergman",
        slug: "ingmar-bergman",
        reviewCount: 3,
        averageGradeValue: 3.3333333333333335,
        reviews: [
          {
            sequence: 942,
            prettyDate: "Sun Dec 13, 2020",
            gradeValue: 3.67,
            title: "Crisis",
            year: 1946,
            slug: "crisis-1946",
          },
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            gradeValue: 4,
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 952,
            prettyDate: "Sun Dec 20, 2020",
            gradeValue: 2.33,
            title: "A Ship to India",
            year: 1947,
            slug: "a-ship-to-india-1947",
          },
        ],
      },
      {
        fullName: "Robert Milton",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 3.165,
        reviews: [
          {
            sequence: 845,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 3,
            title: "Charming Sinners",
            year: 1929,
            slug: "charming-sinners-1929",
          },
          {
            sequence: 858,
            prettyDate: "Sat Aug 22, 2020",
            gradeValue: 3.33,
            title: "Behind the Make-Up",
            year: 1930,
            slug: "behind-the-make-up-1930",
          },
        ],
      },
      {
        fullName: "Lowell Dean",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 3.165,
        reviews: [
          {
            sequence: 878,
            prettyDate: "Fri Oct 2, 2020",
            gradeValue: 4,
            title: "WolfCop",
            year: 2014,
            slug: "wolfcop-2014",
          },
          {
            sequence: 881,
            prettyDate: "Sun Oct 4, 2020",
            gradeValue: 2.33,
            title: "Another WolfCop",
            year: 2017,
            slug: "another-wolfcop-2017",
          },
        ],
      },
      {
        fullName: "Val Guest",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            gradeValue: 3.67,
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            gradeValue: 2.33,
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            gradeValue: 2.33,
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
          {
            sequence: 915,
            prettyDate: "Tue Nov 10, 2020",
            gradeValue: 3.67,
            title: "The Camp on Blood Island",
            year: 1958,
            slug: "the-camp-on-blood-island-1958",
          },
        ],
      },
      {
        fullName: "John Cromwell",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 870,
            prettyDate: "Sun Sep 13, 2020",
            gradeValue: 3,
            title: "For the Defense",
            year: 1930,
            slug: "for-the-defense-1930",
          },
          {
            sequence: 877,
            prettyDate: "Wed Sep 30, 2020",
            gradeValue: 3,
            title: "Street of Chance",
            year: 1930,
            slug: "street-of-chance-1930",
          },
        ],
      },
      {
        fullName: "Adam Green",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 2.835,
        reviews: [
          {
            sequence: 871,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 3,
            title: "Hatchet",
            year: 2006,
            slug: "hatchet-2006",
          },
          {
            sequence: 890,
            prettyDate: "Thu Oct 15, 2020",
            gradeValue: 2.67,
            title: "Hatchet II",
            year: 2010,
            slug: "hatchet-ii-2010",
          },
        ],
      },
      {
        fullName: "Jon Watts",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 2.83,
        reviews: [
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Frank Tuttle",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.776666666666667,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
        ],
      },
      {
        fullName: "Lothar Mendes",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 2.665,
        reviews: [
          {
            sequence: 859,
            prettyDate: "Sat Aug 22, 2020",
            gradeValue: 2.33,
            title: "Interference",
            year: 1928,
            slug: "interference-1928",
          },
          {
            sequence: 925,
            prettyDate: "Wed Nov 25, 2020",
            gradeValue: 3,
            title: "Ladies' Man",
            year: 1931,
            slug: "ladies-man-1931",
          },
        ],
      },
      {
        fullName: "John Ford",
        slug: "john-ford",
        reviewCount: 5,
        averageGradeValue: 2.532,
        reviews: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            gradeValue: 1,
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 867,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 2.33,
            title: "Born Reckless",
            year: 1930,
            slug: "born-reckless-1930",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 3.33,
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
          {
            sequence: 912,
            prettyDate: "Fri Nov 6, 2020",
            gradeValue: 3.67,
            title: "Up the River",
            year: 1930,
            slug: "up-the-river-1930",
          },
        ],
      },
      {
        fullName: "Alfred Hitchcock",
        slug: "alfred-hitchcock",
        reviewCount: 3,
        averageGradeValue: 2.4433333333333334,
        reviews: [
          {
            sequence: 838,
            prettyDate: "Fri Jul 10, 2020",
            gradeValue: 3.33,
            title: "Blackmail",
            year: 1929,
            slug: "blackmail-1929",
          },
          {
            sequence: 876,
            prettyDate: "Mon Sep 28, 2020",
            gradeValue: 3,
            title: "Murder!",
            year: 1930,
            slug: "murder-1930",
          },
          {
            sequence: 909,
            prettyDate: "Mon Nov 2, 2020",
            gradeValue: 1,
            title: "Juno and the Paycock",
            year: 1930,
            slug: "juno-and-the-paycock-1930",
          },
        ],
      },
      {
        fullName: "Lionel Barrymore",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 2.33,
        reviews: [
          {
            sequence: 855,
            prettyDate: "Tue Aug 18, 2020",
            gradeValue: 2.33,
            title: "The Unholy Night",
            year: 1929,
            slug: "the-unholy-night-1929",
          },
          {
            sequence: 895,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 2.33,
            title: "The Sea Bat",
            year: 1930,
            slug: "the-sea-bat-1930",
          },
        ],
      },
      {
        fullName: "Peyton Reed",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 2.165,
        reviews: [
          {
            sequence: 842,
            prettyDate: "Sat Jul 18, 2020",
            gradeValue: 2.33,
            title: "Ant-Man",
            year: 2015,
            slug: "ant-man-2015",
          },
          {
            sequence: 900,
            prettyDate: "Sat Oct 24, 2020",
            gradeValue: 2,
            title: "Ant-Man and the Wasp",
            year: 2018,
            slug: "ant-man-and-the-wasp-2018",
          },
        ],
      },
      {
        fullName: "Irving Cummings",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 1.665,
        reviews: [
          {
            sequence: 837,
            prettyDate: "Thu Jul 9, 2020",
            gradeValue: 2.33,
            title: "Behind That Curtain",
            year: 1929,
            slug: "behind-that-curtain-1929",
          },
          {
            sequence: 928,
            prettyDate: "Fri Nov 27, 2020",
            gradeValue: 1,
            title: "A Holy Terror",
            year: 1931,
            slug: "a-holy-terror-1931",
          },
        ],
      },
    ],
  },
  performers: {
    highestRated: [
      {
        fullName: "Chris Hemsworth",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.798,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 875,
            prettyDate: "Sat Sep 26, 2020",
            gradeValue: 5,
            title: "Thor: Ragnarok",
            year: 2017,
            slug: "thor-ragnarok-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 956,
            prettyDate: "Tue Dec 22, 2020",
            gradeValue: 5.33,
            title: "The Cabin in the Woods",
            year: 2011,
            slug: "the-cabin-in-the-woods-2011",
          },
        ],
      },
      {
        fullName: "Mark Ruffalo",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 4.665,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 875,
            prettyDate: "Sat Sep 26, 2020",
            gradeValue: 5,
            title: "Thor: Ragnarok",
            year: 2017,
            slug: "thor-ragnarok-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Don Cheadle",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 4.4975000000000005,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Scarlett Johansson",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 4.4975000000000005,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Elizabeth Olsen",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 4.4975000000000005,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Robert Downey Jr.",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.264,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Kerry Condon",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.264,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Chris Evans",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.264,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Anthony Mackie",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.064,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 842,
            prettyDate: "Sat Jul 18, 2020",
            gradeValue: 2.33,
            title: "Ant-Man",
            year: 2015,
            slug: "ant-man-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Tom Holland",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.064,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Brian Schaeffer",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3.9975,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Marisa Tomei",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3.7475,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Peter Cushing",
        slug: "peter-cushing",
        reviewCount: 5,
        averageGradeValue: 3.4659999999999997,
        reviews: [
          {
            sequence: 847,
            prettyDate: "Sat Aug 1, 2020",
            gradeValue: 3,
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            slug: "star-wars-episode-iv-a-new-hope-1977",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            gradeValue: 2.33,
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 872,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 5,
            title: "The Curse of Frankenstein",
            year: 1957,
            slug: "the-curse-of-frankenstein-1957",
          },
          {
            sequence: 882,
            prettyDate: "Tue Oct 6, 2020",
            gradeValue: 2.33,
            title: "A Chump at Oxford",
            year: 1939,
            slug: "a-chump-at-oxford-1939",
          },
          {
            sequence: 936,
            prettyDate: "Tue Dec 8, 2020",
            gradeValue: 4.67,
            title: "Horror of Dracula",
            year: 1958,
            slug: "horror-of-dracula-1958",
          },
        ],
      },
      {
        fullName: "Paul Rudd",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3.415,
        reviews: [
          {
            sequence: 842,
            prettyDate: "Sat Jul 18, 2020",
            gradeValue: 2.33,
            title: "Ant-Man",
            year: 2015,
            slug: "ant-man-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 900,
            prettyDate: "Sat Oct 24, 2020",
            gradeValue: 2,
            title: "Ant-Man and the Wasp",
            year: 2018,
            slug: "ant-man-and-the-wasp-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Samuel L. Jackson",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 3.2640000000000002,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 913,
            prettyDate: "Sun Nov 8, 2020",
            gradeValue: 3.33,
            title: "Captain Marvel",
            year: 2019,
            slug: "captain-marvel-2019",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
          {
            sequence: 966,
            prettyDate: "Thu Dec 31, 2020",
            gradeValue: 2.33,
            title: "Glass",
            year: 2019,
            slug: "glass-2019",
          },
        ],
      },
      {
        fullName: "E.H. Calvert",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2.915,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 858,
            prettyDate: "Sat Aug 22, 2020",
            gradeValue: 3.33,
            title: "Behind the Make-Up",
            year: 1930,
            slug: "behind-the-make-up-1930",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
        ],
      },
      {
        fullName: "William Powell",
        slug: "william-powell",
        reviewCount: 11,
        averageGradeValue: 2.847272727272727,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 845,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 3,
            title: "Charming Sinners",
            year: 1929,
            slug: "charming-sinners-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 849,
            prettyDate: "Sun Aug 2, 2020",
            gradeValue: 2,
            title: "Pointed Heels",
            year: 1929,
            slug: "pointed-heels-1929",
          },
          {
            sequence: 858,
            prettyDate: "Sat Aug 22, 2020",
            gradeValue: 3.33,
            title: "Behind the Make-Up",
            year: 1930,
            slug: "behind-the-make-up-1930",
          },
          {
            sequence: 859,
            prettyDate: "Sat Aug 22, 2020",
            gradeValue: 2.33,
            title: "Interference",
            year: 1928,
            slug: "interference-1928",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
          {
            sequence: 870,
            prettyDate: "Sun Sep 13, 2020",
            gradeValue: 3,
            title: "For the Defense",
            year: 1930,
            slug: "for-the-defense-1930",
          },
          {
            sequence: 877,
            prettyDate: "Wed Sep 30, 2020",
            gradeValue: 3,
            title: "Street of Chance",
            year: 1930,
            slug: "street-of-chance-1930",
          },
          {
            sequence: 885,
            prettyDate: "Sat Oct 10, 2020",
            gradeValue: 3.33,
            title: "Shadow of the Law",
            year: 1930,
            slug: "shadow-of-the-law-1930",
          },
          {
            sequence: 925,
            prettyDate: "Wed Nov 25, 2020",
            gradeValue: 3,
            title: "Ladies' Man",
            year: 1931,
            slug: "ladies-man-1931",
          },
        ],
      },
      {
        fullName: "Bela Lugosi",
        slug: "bela-lugosi",
        reviewCount: 6,
        averageGradeValue: 2.831666666666667,
        reviews: [
          {
            sequence: 854,
            prettyDate: "Mon Aug 17, 2020",
            gradeValue: 2.33,
            title: "The Thirteenth Chair",
            year: 1929,
            slug: "the-thirteenth-chair-1929",
          },
          {
            sequence: 880,
            prettyDate: "Sun Oct 4, 2020",
            gradeValue: 4.67,
            title: "Dracula",
            year: 1931,
            slug: "dracula-1931",
          },
          {
            sequence: 886,
            prettyDate: "Sat Oct 10, 2020",
            gradeValue: 3.33,
            title: "Renegades",
            year: 1930,
            slug: "renegades-1930",
          },
          {
            sequence: 922,
            prettyDate: "Tue Nov 24, 2020",
            gradeValue: 2.33,
            title: "Wild Company",
            year: 1930,
            slug: "wild-company-1930",
          },
          {
            sequence: 923,
            prettyDate: "Tue Nov 24, 2020",
            gradeValue: 1,
            title: "Oh, for a Man!",
            year: 1930,
            slug: "oh-for-a-man-1930",
          },
          {
            sequence: 926,
            prettyDate: "Thu Nov 26, 2020",
            gradeValue: 3.33,
            title: "The Black Camel",
            year: 1931,
            slug: "the-black-camel-1931",
          },
        ],
      },
      {
        fullName: "Eugene Pallette",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2.5825,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 849,
            prettyDate: "Sun Aug 2, 2020",
            gradeValue: 2,
            title: "Pointed Heels",
            year: 1929,
            slug: "pointed-heels-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
        ],
      },
      {
        fullName: "Boris Karloff",
        slug: "boris-karloff",
        reviewCount: 4,
        averageGradeValue: 2.4975,
        reviews: [
          {
            sequence: 837,
            prettyDate: "Thu Jul 9, 2020",
            gradeValue: 2.33,
            title: "Behind That Curtain",
            year: 1929,
            slug: "behind-that-curtain-1929",
          },
          {
            sequence: 889,
            prettyDate: "Sun Oct 11, 2020",
            gradeValue: 2,
            title: "Cracked Nuts",
            year: 1931,
            slug: "cracked-nuts-1931",
          },
          {
            sequence: 895,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 2.33,
            title: "The Sea Bat",
            year: 1930,
            slug: "the-sea-bat-1930",
          },
          {
            sequence: 919,
            prettyDate: "Wed Nov 18, 2020",
            gradeValue: 3.33,
            title: "The Criminal Code",
            year: 1930,
            slug: "the-criminal-code-1930",
          },
        ],
      },
    ],
  },
  writers: {
    highestRated: [
      {
        fullName: "Christopher Markus",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.886666666666667,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Stephen McFeely",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.886666666666667,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Jimmy Sangster",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.333333333333333,
        reviews: [
          {
            sequence: 853,
            prettyDate: "Sun Aug 16, 2020",
            gradeValue: 3.33,
            title: "X the Unknown",
            year: 1956,
            slug: "x-the-unknown-1956",
          },
          {
            sequence: 872,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 5,
            title: "The Curse of Frankenstein",
            year: 1957,
            slug: "the-curse-of-frankenstein-1957",
          },
          {
            sequence: 936,
            prettyDate: "Tue Dec 8, 2020",
            gradeValue: 4.67,
            title: "Horror of Dracula",
            year: 1958,
            slug: "horror-of-dracula-1958",
          },
        ],
      },
      {
        fullName: "Roberto Gianviti",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3.6675,
        reviews: [
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            gradeValue: 4,
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 3.67,
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            gradeValue: 3.33,
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            gradeValue: 3.67,
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
        ],
      },
      {
        fullName: "Charles Bennett",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 3.665,
        reviews: [
          {
            sequence: 838,
            prettyDate: "Fri Jul 10, 2020",
            gradeValue: 3.33,
            title: "Blackmail",
            year: 1929,
            slug: "blackmail-1929",
          },
          {
            sequence: 894,
            prettyDate: "Mon Oct 19, 2020",
            gradeValue: 4,
            title: "Curse of the Demon",
            year: 1957,
            slug: "curse-of-the-demon-1957",
          },
        ],
      },
      {
        fullName: "Lucio Fulci",
        slug: "lucio-fulci",
        reviewCount: 5,
        averageGradeValue: 3.6,
        reviews: [
          {
            sequence: 873,
            prettyDate: "Mon Sep 21, 2020",
            gradeValue: 3.33,
            title: "Massacre Time",
            year: 1966,
            slug: "the-brute-and-the-beast-1966",
          },
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            gradeValue: 4,
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 3.67,
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            gradeValue: 3.33,
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            gradeValue: 3.67,
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
        ],
      },
      {
        fullName: "Ingmar Bergman",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 3.3333333333333335,
        reviews: [
          {
            sequence: 942,
            prettyDate: "Sun Dec 13, 2020",
            gradeValue: 3.67,
            title: "Crisis",
            year: 1946,
            slug: "crisis-1946",
          },
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            gradeValue: 4,
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 952,
            prettyDate: "Sun Dec 20, 2020",
            gradeValue: 2.33,
            title: "A Ship to India",
            year: 1947,
            slug: "a-ship-to-india-1947",
          },
        ],
      },
      {
        fullName: "Val Guest",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            gradeValue: 3.67,
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            gradeValue: 2.33,
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            gradeValue: 2.33,
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
          {
            sequence: 915,
            prettyDate: "Tue Nov 10, 2020",
            gradeValue: 3.67,
            title: "The Camp on Blood Island",
            year: 1958,
            slug: "the-camp-on-blood-island-1958",
          },
        ],
      },
      {
        fullName: "Adam Green",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 871,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 3,
            title: "Hatchet",
            year: 2006,
            slug: "hatchet-2006",
          },
          {
            sequence: 890,
            prettyDate: "Thu Oct 15, 2020",
            gradeValue: 2.67,
            title: "Hatchet II",
            year: 2010,
            slug: "hatchet-ii-2010",
          },
          {
            sequence: 920,
            prettyDate: "Thu Nov 19, 2020",
            gradeValue: 3.33,
            title: "Hatchet III",
            year: 2013,
            slug: "hatchet-iii-2013",
          },
        ],
      },
      {
        fullName: "Dudley Nichols",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.9966666666666666,
        reviews: [
          {
            sequence: 867,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 2.33,
            title: "Born Reckless",
            year: 1930,
            slug: "born-reckless-1930",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 3.33,
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 926,
            prettyDate: "Thu Nov 26, 2020",
            gradeValue: 3.33,
            title: "The Black Camel",
            year: 1931,
            slug: "the-black-camel-1931",
          },
        ],
      },
      {
        fullName: "Bruce Feirstein",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.89,
        reviews: [
          {
            sequence: 850,
            prettyDate: "Tue Aug 4, 2020",
            gradeValue: 3.67,
            title: "GoldenEye",
            year: 1995,
            slug: "goldeneye-1995",
          },
          {
            sequence: 851,
            prettyDate: "Thu Aug 6, 2020",
            gradeValue: 2.33,
            title: "Tomorrow Never Dies",
            year: 1997,
            slug: "tomorrow-never-dies-1997",
          },
          {
            sequence: 852,
            prettyDate: "Thu Aug 6, 2020",
            gradeValue: 2.67,
            title: "The World Is Not Enough",
            year: 1999,
            slug: "the-world-is-not-enough-1999",
          },
        ],
      },
      {
        fullName: "Earl Derr Biggers",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 2.83,
        reviews: [
          {
            sequence: 837,
            prettyDate: "Thu Jul 9, 2020",
            gradeValue: 2.33,
            title: "Behind That Curtain",
            year: 1929,
            slug: "behind-that-curtain-1929",
          },
          {
            sequence: 926,
            prettyDate: "Thu Nov 26, 2020",
            gradeValue: 3.33,
            title: "The Black Camel",
            year: 1931,
            slug: "the-black-camel-1931",
          },
        ],
      },
      {
        fullName: "S.S. Van Dine",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.776666666666667,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
        ],
      },
      {
        fullName: "Nigel Kneale",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.776666666666667,
        reviews: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            gradeValue: 3.67,
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            gradeValue: 2.33,
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            gradeValue: 2.33,
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
        ],
      },
      {
        fullName: "Chris McKenna",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.5533333333333332,
        reviews: [
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 900,
            prettyDate: "Sat Oct 24, 2020",
            gradeValue: 2,
            title: "Ant-Man and the Wasp",
            year: 2018,
            slug: "ant-man-and-the-wasp-2018",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Erik Sommers",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.5533333333333332,
        reviews: [
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 900,
            prettyDate: "Sat Oct 24, 2020",
            gradeValue: 2,
            title: "Ant-Man and the Wasp",
            year: 2018,
            slug: "ant-man-and-the-wasp-2018",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Alfred Hitchcock",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.4433333333333334,
        reviews: [
          {
            sequence: 838,
            prettyDate: "Fri Jul 10, 2020",
            gradeValue: 3.33,
            title: "Blackmail",
            year: 1929,
            slug: "blackmail-1929",
          },
          {
            sequence: 876,
            prettyDate: "Mon Sep 28, 2020",
            gradeValue: 3,
            title: "Murder!",
            year: 1930,
            slug: "murder-1930",
          },
          {
            sequence: 909,
            prettyDate: "Mon Nov 2, 2020",
            gradeValue: 1,
            title: "Juno and the Paycock",
            year: 1930,
            slug: "juno-and-the-paycock-1930",
          },
        ],
      },
      {
        fullName: "Wilbur Morse Jr.",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 2.33,
        reviews: [
          {
            sequence: 837,
            prettyDate: "Thu Jul 9, 2020",
            gradeValue: 2.33,
            title: "Behind That Curtain",
            year: 1929,
            slug: "behind-that-curtain-1929",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
        ],
      },
      {
        fullName: "James Kevin McGuinness",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.22,
        reviews: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            gradeValue: 1,
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 3.33,
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
        ],
      },
      {
        fullName: "John Stone",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 1.8866666666666667,
        reviews: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            gradeValue: 1,
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
          {
            sequence: 922,
            prettyDate: "Tue Nov 24, 2020",
            gradeValue: 2.33,
            title: "Wild Company",
            year: 1930,
            slug: "wild-company-1930",
          },
        ],
      },
    ],
  },
  year: {
    nodes: [
      {
        year: "all",
      },
      {
        year: "2021",
      },
      {
        year: "2020",
      },
    ],
  },
};
