---
plugins:
  - stylelint-order
extends:
  - stylelint-config-recommended
  - stylelint-config-standard-scss
  - stylelint-config-prettier
rules:
  order/properties-alphabetical-order: true
  property-no-unknown:
    - true
  scss/dollar-variable-pattern: "^[a-z][a-zA-Z0-9]+$"
  selector-class-pattern:
    - "^[a-z][a-zA-Z0-9]+Css$"
    - message: Selector should be written in lowerCamelCase and end with Css (selector-class-pattern)
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        # CSS Modules :global scope
        # https://github.com/css-modules/css-modules#exceptions
        - global
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands: ["/grid/", "/flex/"]
  max-empty-lines: 1
  block-closing-brace-empty-line-before: never
  custom-property-pattern: null
  scss/at-else-closing-brace-newline-after: null
  scss/at-else-closing-brace-space-after: null
  scss/at-else-empty-line-before: null
  scss/at-else-if-parentheses-space-before: null
  scss/at-function-parentheses-space-before: null
  scss/at-if-closing-brace-newline-after: null
  scss/at-if-closing-brace-space-after: null
  scss/at-mixin-parentheses-space-before: null
  scss/dollar-variable-colon-newline-after: null
  scss/dollar-variable-colon-space-after: null
  scss/dollar-variable-colon-space-before: null
  scss/operator-no-newline-after: null
  scss/operator-no-newline-before: null
  scss/operator-no-unspaced: null
