yarnPath: .yarn/releases/yarn-4.2.1.cjs
nodeLinker: node-modules

logFilters:
  - code: "YN0086"
    level: "error"
  - pattern: "react is listed by your project with version 18.2.0, which doesn't satisfy what gatsby"
    level: "discard"
