[[redirects]]
  from = "/watchlist/cast/*"
  to = "/watchlist/performers/:splat"
  status = 301

[[redirects]]
  from = "/cast-and-crew/christopher-lee-i"
  to = "/watchlist/performers/christopher-lee"
  status = 301

[[redirects]]
  from = "/cast-and-crew/humphrey-bogart"
  to = "/watchlist/performers/humphrey-bogart"
  status = 301

[[redirects]]
  from = "/cast-and-crew/john-wayne-i"
  to = "/watchlist/performers/john-wayne"
  status = 301

[[redirects]]
  from = "/browse/reviews/dont-torture-a-duckling-1972"
  to = "/reviews/dont-torture-a-duckling-1972"
  status = 301

[[redirects]]
  from = "/browse/reviews/up-the-river-1930"
  to = "/reviews/up-the-river-1930"
  status = 301

[[redirects]]
  from = "/browse/reviews/kill-a-dragon-1967"
  to = "/reviews/kill-a-dragon-1967"
  status = 301

[[redirects]]
  from = "/reviews/island-of-death-1977"
  to = "/reviews/island-of-death-1976"
  status = 301

[[redirects]]
  from = "/reviews/curse-of-the-demon-1958"
  to = "/reviews/curse-of-the-demon-1957"
  status = 301

[[redirects]]
  from = "/reviews/l-age-d-or-1930"
  to = "/reviews/lage-dor-1930"
  status = 301


[[redirects]]
  from = "/wp-login.php"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/apple-touch-icon.png"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/apple-touch-icon-120x120.png"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/apple-touch-icon-152x152.png"
  to = "/apple-touch-icon-152x152.png"
  status = 410

[[redirects]]
  from = "/apple-touch-icon-120x120-precomposed.png"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/apple-touch-icon-precomposed.png"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/cast-and-crew/yakima-canutt"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/cast-and-crew/betta-st-john"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/cast-and-crew/maureen-o-sullivan-i"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/watchlist/cast/bill-murray"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/cast-and-crew/bill-finger-ii"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/cast-and-crew/martin-kitrosser"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/images/5-stars-4661cb2a.svg"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/apple-touch-icon-152x152.png"
  to = "/gone"
  status = 410

[[redirects]]
  from = "/cast-and-crew/bob-kane-i"
  to = "/gone"
  status = 410
