[[redirects]]
  from = "/cast-and-crew/christopher-lee-i"
  to = "/watchlist/cast/christopher-lee"
  status = 301

[[redirects]]
  from = "/cast-and-crew/humphrey-bogart"
  to = "/watchlist/cast/humphrey-bogart"
  status = 301