export default {
  overall: {
    averageWordsPerReview: 136.68345323741008,
    reviewCount: 278,
  },
  gradeDistribution: {
    stats: [
      {
        grade: "A+",
        reviewCount: 6,
      },
      {
        grade: "A",
        reviewCount: 5,
      },
      {
        grade: "A-",
        reviewCount: 8,
      },
      {
        grade: "B+",
        reviewCount: 15,
      },
      {
        grade: "B",
        reviewCount: 21,
      },
      {
        grade: "B-",
        reviewCount: 25,
      },
      {
        grade: "C+",
        reviewCount: 49,
      },
      {
        grade: "C",
        reviewCount: 33,
      },
      {
        grade: "C-",
        reviewCount: 20,
      },
      {
        grade: "D+",
        reviewCount: 60,
      },
      {
        grade: "D",
        reviewCount: 16,
      },
      {
        grade: "D-",
        reviewCount: 1,
      },
      {
        grade: "F",
        reviewCount: 19,
      },
    ],
  },
  decade: {
    stats: [
      {
        decade: "1920s",
        averageGradeValue: 2.391818181818181,
      },
      {
        decade: "1930s",
        averageGradeValue: 2.654918032786885,
      },
      {
        decade: "1940s",
        averageGradeValue: 2.3830769230769224,
      },
      {
        decade: "1950s",
        averageGradeValue: 3.229615384615384,
      },
      {
        decade: "1960s",
        averageGradeValue: 2.901176470588235,
      },
      {
        decade: "1970s",
        averageGradeValue: 3.1144827586206896,
      },
      {
        decade: "1980s",
        averageGradeValue: 3.4525,
      },
      {
        decade: "1990s",
        averageGradeValue: 2.9278571428571425,
      },
      {
        decade: "2000s",
        averageGradeValue: 3.2206666666666663,
      },
      {
        decade: "2010s",
        averageGradeValue: 3.4776363636363636,
      },
      {
        decade: "2020s",
        averageGradeValue: 2.5544444444444445,
      },
    ],
  },
  directors: {
    highestRated: [
      {
        fullName: "Anthony Russo",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.886666666666667,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Joe Russo",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.886666666666667,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Michael Haneke",
        slug: "michael-haneke",
        reviewCount: 3,
        averageGradeValue: 4.223333333333334,
        reviews: [
          {
            sequence: 998,
            prettyDate: "Tue Jan 26, 2021",
            gradeValue: 4.67,
            title: "The Seventh Continent",
            year: 1989,
            slug: "the-seventh-continent-1989",
          },
          {
            sequence: 1053,
            prettyDate: "Thu Mar 18, 2021",
            gradeValue: 4.67,
            title: "Benny's Video",
            year: 1992,
            slug: "bennys-video-1992",
          },
          {
            sequence: 1067,
            prettyDate: "Mon Mar 29, 2021",
            gradeValue: 3.33,
            title: "71 Fragments of a Chronology of Chance",
            year: 1994,
            slug: "71-fragments-of-a-chronology-of-chance-1994",
          },
        ],
      },
      {
        fullName: "Howard Hawks",
        slug: "howard-hawks",
        reviewCount: 3,
        averageGradeValue: 4.11,
        reviews: [
          {
            sequence: 869,
            prettyDate: "Sun Sep 13, 2020",
            gradeValue: 3.67,
            title: "The Dawn Patrol",
            year: 1930,
            slug: "the-dawn-patrol-1930",
          },
          {
            sequence: 919,
            prettyDate: "Wed Nov 18, 2020",
            gradeValue: 3.33,
            title: "The Criminal Code",
            year: 1930,
            slug: "the-criminal-code-1930",
          },
          {
            sequence: 1001,
            prettyDate: "Fri Jan 29, 2021",
            gradeValue: 5.33,
            title: "Rio Bravo",
            year: 1959,
            slug: "rio-bravo-1959",
          },
        ],
      },
      {
        fullName: "Zack Snyder",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4,
        reviews: [
          {
            sequence: 1054,
            prettyDate: "Fri Mar 19, 2021",
            gradeValue: 4,
            title: "Zack Snyder's Justice League",
            year: 2021,
            slug: "zack-snyders-justice-league-2021",
          },
          {
            sequence: 1064,
            prettyDate: "Sat Mar 27, 2021",
            gradeValue: 3.67,
            title: "Batman v Superman: Dawn of Justice",
            year: 2016,
            slug: "batman-v-superman-dawn-of-justice-2016",
          },
          {
            sequence: 1084,
            prettyDate: "Sat Apr 17, 2021",
            gradeValue: 4.33,
            title: "Watchmen",
            year: 2009,
            slug: "watchmen-2009",
          },
        ],
      },
      {
        fullName: "Lucio Fulci",
        slug: "lucio-fulci",
        reviewCount: 6,
        averageGradeValue: 3.388333333333333,
        reviews: [
          {
            sequence: 873,
            prettyDate: "Mon Sep 21, 2020",
            gradeValue: 3.33,
            title: "Massacre Time",
            year: 1966,
            slug: "the-brute-and-the-beast-1966",
          },
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            gradeValue: 4,
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 3.67,
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            gradeValue: 3.33,
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            gradeValue: 3.67,
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
          {
            sequence: 1060,
            prettyDate: "Fri Mar 26, 2021",
            gradeValue: 2.33,
            title: "White Fang",
            year: 1973,
            slug: "white-fang-1973",
          },
        ],
      },
      {
        fullName: "James Whale",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 3.3333333333333335,
        reviews: [
          {
            sequence: 1029,
            prettyDate: "Thu Feb 25, 2021",
            gradeValue: 2.67,
            title: "Waterloo Bridge",
            year: 1931,
            slug: "waterloo-bridge-1931",
          },
          {
            sequence: 1087,
            prettyDate: "Tue Apr 20, 2021",
            gradeValue: 4.33,
            title: "Frankenstein",
            year: 1931,
            slug: "frankenstein-1931",
          },
          {
            sequence: 1099,
            prettyDate: "Mon May 10, 2021",
            gradeValue: 3,
            title: "The Man in the Iron Mask",
            year: 1939,
            slug: "the-man-in-the-iron-mask-1939",
          },
        ],
      },
      {
        fullName: "Tod Browning",
        slug: "tod-browning",
        reviewCount: 4,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 854,
            prettyDate: "Mon Aug 17, 2020",
            gradeValue: 2.33,
            title: "The Thirteenth Chair",
            year: 1929,
            slug: "the-thirteenth-chair-1929",
          },
          {
            sequence: 880,
            prettyDate: "Sun Oct 4, 2020",
            gradeValue: 4.67,
            title: "Dracula",
            year: 1931,
            slug: "dracula-1931",
          },
          {
            sequence: 967,
            prettyDate: "Fri Jan 1, 2021",
            gradeValue: 2,
            title: "Outside the Law",
            year: 1930,
            slug: "outside-the-law-1930",
          },
          {
            sequence: 988,
            prettyDate: "Sun Jan 17, 2021",
            gradeValue: 3,
            title: "Iron Man",
            year: 1931,
            slug: "iron-man-1931",
          },
        ],
      },
      {
        fullName: "Val Guest",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            gradeValue: 3.67,
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            gradeValue: 2.33,
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            gradeValue: 2.33,
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
          {
            sequence: 915,
            prettyDate: "Tue Nov 10, 2020",
            gradeValue: 3.67,
            title: "The Camp on Blood Island",
            year: 1958,
            slug: "the-camp-on-blood-island-1958",
          },
        ],
      },
      {
        fullName: "Don Mancini",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.9966666666666666,
        reviews: [
          {
            sequence: 1092,
            prettyDate: "Sun Apr 25, 2021",
            gradeValue: 3.33,
            title: "Seed of Chucky",
            year: 2004,
            slug: "seed-of-chucky-2004",
          },
          {
            sequence: 1105,
            prettyDate: "Sun May 16, 2021",
            gradeValue: 3.33,
            title: "Curse of Chucky",
            year: 2013,
            slug: "curse-of-chucky-2013",
          },
          {
            sequence: 1110,
            prettyDate: "Thu Jun 3, 2021",
            gradeValue: 2.33,
            title: "Cult of Chucky",
            year: 2017,
            slug: "cult-of-chucky-2017",
          },
        ],
      },
      {
        fullName: "Ingmar Bergman",
        slug: "ingmar-bergman",
        reviewCount: 15,
        averageGradeValue: 2.887333333333333,
        reviews: [
          {
            sequence: 942,
            prettyDate: "Sun Dec 13, 2020",
            gradeValue: 3.67,
            title: "Crisis",
            year: 1946,
            slug: "crisis-1946",
          },
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            gradeValue: 4,
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 952,
            prettyDate: "Sun Dec 20, 2020",
            gradeValue: 2.33,
            title: "A Ship to India",
            year: 1947,
            slug: "a-ship-to-india-1947",
          },
          {
            sequence: 976,
            prettyDate: "Fri Jan 8, 2021",
            gradeValue: 2.33,
            title: "Music in Darkness",
            year: 1948,
            slug: "music-in-darkness-1948",
          },
          {
            sequence: 981,
            prettyDate: "Mon Jan 11, 2021",
            gradeValue: 2.33,
            title: "Port of Call",
            year: 1948,
            slug: "port-of-call-1948",
          },
          {
            sequence: 1004,
            prettyDate: "Mon Feb 1, 2021",
            gradeValue: 2.33,
            title: "Prison",
            year: 1949,
            slug: "prison-1949",
          },
          {
            sequence: 1021,
            prettyDate: "Wed Feb 17, 2021",
            gradeValue: 1,
            title: "Thirst",
            year: 1949,
            slug: "thirst-1949",
          },
          {
            sequence: 1035,
            prettyDate: "Mon Mar 1, 2021",
            gradeValue: 3.33,
            title: "To Joy",
            year: 1950,
            slug: "to-joy-1950",
          },
          {
            sequence: 1050,
            prettyDate: "Mon Mar 15, 2021",
            gradeValue: 1,
            title: "This Can't Happen Here",
            year: 1950,
            slug: "this-cant-happen-here-1950",
          },
          {
            sequence: 1058,
            prettyDate: "Wed Mar 24, 2021",
            gradeValue: 3.33,
            title: "Summer Interlude",
            year: 1951,
            slug: "summer-interlude-1951",
          },
          {
            sequence: 1069,
            prettyDate: "Thu Apr 1, 2021",
            gradeValue: 2.67,
            title: "Kvinnors väntan",
            year: 1952,
            slug: "waiting-women-1952",
          },
          {
            sequence: 1079,
            prettyDate: "Mon Apr 12, 2021",
            gradeValue: 4.33,
            title: "Summer with Monika",
            year: 1953,
            slug: "summer-with-monika-1953",
          },
          {
            sequence: 1089,
            prettyDate: "Thu Apr 22, 2021",
            gradeValue: 4.33,
            title: "Sawdust and Tinsel",
            year: 1953,
            slug: "sawdust-and-tinsel-1953",
          },
          {
            sequence: 1094,
            prettyDate: "Wed Apr 28, 2021",
            gradeValue: 3,
            title: "A Lesson in Love",
            year: 1954,
            slug: "a-lesson-in-love-1954",
          },
          {
            sequence: 1098,
            prettyDate: "Tue May 4, 2021",
            gradeValue: 3.33,
            title: "Dreams",
            year: 1955,
            slug: "dreams-1955",
          },
        ],
      },
      {
        fullName: "Frank Tuttle",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2.8325,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
          {
            sequence: 1062,
            prettyDate: "Sat Mar 27, 2021",
            gradeValue: 3,
            title: "This Is the Night",
            year: 1932,
            slug: "this-is-the-night-1932",
          },
        ],
      },
      {
        fullName: "Bryan Singer",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2.8325,
        reviews: [
          {
            sequence: 978,
            prettyDate: "Sat Jan 9, 2021",
            gradeValue: 4,
            title: "X-Men",
            year: 2000,
            slug: "x-men-2000",
          },
          {
            sequence: 986,
            prettyDate: "Sat Jan 16, 2021",
            gradeValue: 3,
            title: "X2: X-Men United",
            year: 2003,
            slug: "x2-x-men-united-2003",
          },
          {
            sequence: 1024,
            prettyDate: "Sat Feb 20, 2021",
            gradeValue: 3.33,
            title: "X-Men: Days of Future Past",
            year: 2014,
            slug: "x-men-days-of-future-past-2014",
          },
          {
            sequence: 1040,
            prettyDate: "Sat Mar 6, 2021",
            gradeValue: 1,
            title: "X-Men: Apocalypse",
            year: 2016,
            slug: "x-men-apocalypse-2016",
          },
        ],
      },
      {
        fullName: "Adam Green",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.6666666666666665,
        reviews: [
          {
            sequence: 871,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 3,
            title: "Hatchet",
            year: 2006,
            slug: "hatchet-2006",
          },
          {
            sequence: 890,
            prettyDate: "Thu Oct 15, 2020",
            gradeValue: 2.67,
            title: "Hatchet II",
            year: 2010,
            slug: "hatchet-ii-2010",
          },
          {
            sequence: 987,
            prettyDate: "Sat Jan 16, 2021",
            gradeValue: 2.33,
            title: "Victor Crowley",
            year: 2017,
            slug: "victor-crowley-2017",
          },
        ],
      },
      {
        fullName: "Brian De Palma",
        slug: "brian-de-palma",
        reviewCount: 7,
        averageGradeValue: 2.5228571428571427,
        reviews: [
          {
            sequence: 969,
            prettyDate: "Fri Jan 1, 2021",
            gradeValue: 3.67,
            title: "Murder à la Mod",
            year: 1968,
            slug: "murder-a-la-mod-1968",
          },
          {
            sequence: 1006,
            prettyDate: "Wed Feb 3, 2021",
            gradeValue: 2,
            title: "Greetings",
            year: 1968,
            slug: "greetings-1968",
          },
          {
            sequence: 1038,
            prettyDate: "Thu Mar 4, 2021",
            gradeValue: 2.33,
            title: "The Wedding Party",
            year: 1969,
            slug: "the-wedding-party-1969",
          },
          {
            sequence: 1056,
            prettyDate: "Sun Mar 21, 2021",
            gradeValue: 1,
            title: "Dionysus in '69",
            year: 1970,
            slug: "dionysus-in-69-1970",
          },
          {
            sequence: 1068,
            prettyDate: "Wed Mar 31, 2021",
            gradeValue: 2.33,
            title: "Hi, Mom!",
            year: 1970,
            slug: "hi-mom-1970",
          },
          {
            sequence: 1082,
            prettyDate: "Thu Apr 15, 2021",
            gradeValue: 3,
            title: "Get to Know Your Rabbit",
            year: 1972,
            slug: "get-to-know-your-rabbit-1972",
          },
          {
            sequence: 1095,
            prettyDate: "Thu Apr 29, 2021",
            gradeValue: 3.33,
            title: "Sisters",
            year: 1972,
            slug: "sisters-1972",
          },
        ],
      },
      {
        fullName: "John Ford",
        slug: "john-ford",
        reviewCount: 7,
        averageGradeValue: 2.474285714285714,
        reviews: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            gradeValue: 1,
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 867,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 2.33,
            title: "Born Reckless",
            year: 1930,
            slug: "born-reckless-1930",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 3.33,
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
          {
            sequence: 912,
            prettyDate: "Fri Nov 6, 2020",
            gradeValue: 3.67,
            title: "Up the River",
            year: 1930,
            slug: "up-the-river-1930",
          },
          {
            sequence: 975,
            prettyDate: "Thu Jan 7, 2021",
            gradeValue: 2.33,
            title: "Seas Beneath",
            year: 1931,
            slug: "seas-beneath-1931",
          },
          {
            sequence: 1088,
            prettyDate: "Wed Apr 21, 2021",
            gradeValue: 2.33,
            title: "Arrowsmith",
            year: 1931,
            slug: "arrowsmith-1931",
          },
        ],
      },
      {
        fullName: "David Cronenberg",
        slug: "david-cronenberg",
        reviewCount: 4,
        averageGradeValue: 2.4175,
        reviews: [
          {
            sequence: 964,
            prettyDate: "Sat Dec 26, 2020",
            gradeValue: 2,
            title: "Stereo (Tile 3B of a CAEE Educational Mosaic)",
            year: 1969,
            slug: "stereo-tile-3b-of-a-caee-educational-mosaic-1969",
          },
          {
            sequence: 972,
            prettyDate: "Sun Jan 3, 2021",
            gradeValue: 2.33,
            title: "Crimes of the Future",
            year: 1970,
            slug: "crimes-of-the-future-1970",
          },
          {
            sequence: 1000,
            prettyDate: "Thu Jan 28, 2021",
            gradeValue: 2.67,
            title: "Shivers",
            year: 1975,
            slug: "shivers-1975",
          },
          {
            sequence: 1007,
            prettyDate: "Thu Feb 4, 2021",
            gradeValue: 2.67,
            title: "Rabid",
            year: 1977,
            slug: "rabid-1977",
          },
        ],
      },
      {
        fullName: "Mervyn LeRoy",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 2.332,
        reviews: [
          {
            sequence: 892,
            prettyDate: "Fri Oct 16, 2020",
            gradeValue: 3.33,
            title: "Big City Blues",
            year: 1932,
            slug: "big-city-blues-1932",
          },
          {
            sequence: 1030,
            prettyDate: "Thu Feb 25, 2021",
            gradeValue: 2.33,
            title: "Five Star Final",
            year: 1931,
            slug: "five-star-final-1931",
          },
          {
            sequence: 1034,
            prettyDate: "Sun Feb 28, 2021",
            gradeValue: 1,
            title: "Broadminded",
            year: 1931,
            slug: "broadminded-1931",
          },
          {
            sequence: 1097,
            prettyDate: "Mon May 3, 2021",
            gradeValue: 2.33,
            title: "Tonight or Never",
            year: 1931,
            slug: "tonight-or-never-1931",
          },
          {
            sequence: 1100,
            prettyDate: "Wed May 12, 2021",
            gradeValue: 2.67,
            title: "High Pressure",
            year: 1932,
            slug: "high-pressure-1932",
          },
        ],
      },
      {
        fullName: "Alfred Hitchcock",
        slug: "alfred-hitchcock",
        reviewCount: 5,
        averageGradeValue: 2.266,
        reviews: [
          {
            sequence: 838,
            prettyDate: "Fri Jul 10, 2020",
            gradeValue: 3.33,
            title: "Blackmail",
            year: 1929,
            slug: "blackmail-1929",
          },
          {
            sequence: 876,
            prettyDate: "Mon Sep 28, 2020",
            gradeValue: 3,
            title: "Murder!",
            year: 1930,
            slug: "murder-1930",
          },
          {
            sequence: 909,
            prettyDate: "Mon Nov 2, 2020",
            gradeValue: 1,
            title: "Juno and the Paycock",
            year: 1930,
            slug: "juno-and-the-paycock-1930",
          },
          {
            sequence: 979,
            prettyDate: "Sat Jan 9, 2021",
            gradeValue: 2,
            title: "The Skin Game",
            year: 1931,
            slug: "the-skin-game-1931",
          },
          {
            sequence: 1093,
            prettyDate: "Tue Apr 27, 2021",
            gradeValue: 2,
            title: "East of Shanghai",
            year: 1931,
            slug: "east-of-shanghai-1931",
          },
        ],
      },
      {
        fullName: "Irving Cummings",
        slug: null,
        reviewCount: 2,
        averageGradeValue: 1.665,
        reviews: [
          {
            sequence: 837,
            prettyDate: "Thu Jul 9, 2020",
            gradeValue: 2.33,
            title: "Behind That Curtain",
            year: 1929,
            slug: "behind-that-curtain-1929",
          },
          {
            sequence: 928,
            prettyDate: "Fri Nov 27, 2020",
            gradeValue: 1,
            title: "A Holy Terror",
            year: 1931,
            slug: "a-holy-terror-1931",
          },
        ],
      },
    ],
  },
  performers: {
    highestRated: [
      {
        fullName: "Chris Hemsworth",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.798,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 875,
            prettyDate: "Sat Sep 26, 2020",
            gradeValue: 5,
            title: "Thor: Ragnarok",
            year: 2017,
            slug: "thor-ragnarok-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 956,
            prettyDate: "Tue Dec 22, 2020",
            gradeValue: 5.33,
            title: "The Cabin in the Woods",
            year: 2011,
            slug: "the-cabin-in-the-woods-2011",
          },
        ],
      },
      {
        fullName: "Robert Downey Jr.",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.264,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Kerry Condon",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.264,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Chris Evans",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.264,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Anthony Mackie",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.064,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 842,
            prettyDate: "Sat Jul 18, 2020",
            gradeValue: 2.33,
            title: "Ant-Man",
            year: 2015,
            slug: "ant-man-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Tom Holland",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 4.064,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            gradeValue: 3.33,
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Peter Cushing",
        slug: "peter-cushing",
        reviewCount: 6,
        averageGradeValue: 3.388333333333333,
        reviews: [
          {
            sequence: 847,
            prettyDate: "Sat Aug 1, 2020",
            gradeValue: 3,
            title: "Star Wars: Episode IV - A New Hope",
            year: 1977,
            slug: "star-wars-episode-iv-a-new-hope-1977",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            gradeValue: 2.33,
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 872,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 5,
            title: "The Curse of Frankenstein",
            year: 1957,
            slug: "the-curse-of-frankenstein-1957",
          },
          {
            sequence: 882,
            prettyDate: "Tue Oct 6, 2020",
            gradeValue: 2.33,
            title: "A Chump at Oxford",
            year: 1939,
            slug: "a-chump-at-oxford-1939",
          },
          {
            sequence: 936,
            prettyDate: "Tue Dec 8, 2020",
            gradeValue: 4.67,
            title: "Horror of Dracula",
            year: 1958,
            slug: "horror-of-dracula-1958",
          },
          {
            sequence: 1099,
            prettyDate: "Mon May 10, 2021",
            gradeValue: 3,
            title: "The Man in the Iron Mask",
            year: 1939,
            slug: "the-man-in-the-iron-mask-1939",
          },
        ],
      },
      {
        fullName: "Gunnar Björnstrand",
        slug: null,
        reviewCount: 6,
        averageGradeValue: 3.276666666666666,
        reviews: [
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            gradeValue: 4,
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 976,
            prettyDate: "Fri Jan 8, 2021",
            gradeValue: 2.33,
            title: "Music in Darkness",
            year: 1948,
            slug: "music-in-darkness-1948",
          },
          {
            sequence: 1069,
            prettyDate: "Thu Apr 1, 2021",
            gradeValue: 2.67,
            title: "Kvinnors väntan",
            year: 1952,
            slug: "waiting-women-1952",
          },
          {
            sequence: 1089,
            prettyDate: "Thu Apr 22, 2021",
            gradeValue: 4.33,
            title: "Sawdust and Tinsel",
            year: 1953,
            slug: "sawdust-and-tinsel-1953",
          },
          {
            sequence: 1094,
            prettyDate: "Wed Apr 28, 2021",
            gradeValue: 3,
            title: "A Lesson in Love",
            year: 1954,
            slug: "a-lesson-in-love-1954",
          },
          {
            sequence: 1098,
            prettyDate: "Tue May 4, 2021",
            gradeValue: 3.33,
            title: "Dreams",
            year: 1955,
            slug: "dreams-1955",
          },
        ],
      },
      {
        fullName: "Samuel L. Jackson",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 3.2640000000000002,
        reviews: [
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            gradeValue: 3.33,
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 913,
            prettyDate: "Sun Nov 8, 2020",
            gradeValue: 3.33,
            title: "Captain Marvel",
            year: 2019,
            slug: "captain-marvel-2019",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            gradeValue: 2.33,
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
          {
            sequence: 966,
            prettyDate: "Thu Dec 31, 2020",
            gradeValue: 2.33,
            title: "Glass",
            year: 2019,
            slug: "glass-2019",
          },
        ],
      },
      {
        fullName: "Kane Hodder",
        slug: null,
        reviewCount: 6,
        averageGradeValue: 3.1099999999999994,
        reviews: [
          {
            sequence: 871,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 3,
            title: "Hatchet",
            year: 2006,
            slug: "hatchet-2006",
          },
          {
            sequence: 890,
            prettyDate: "Thu Oct 15, 2020",
            gradeValue: 2.67,
            title: "Hatchet II",
            year: 2010,
            slug: "hatchet-ii-2010",
          },
          {
            sequence: 920,
            prettyDate: "Thu Nov 19, 2020",
            gradeValue: 3.33,
            title: "Hatchet III",
            year: 2013,
            slug: "hatchet-iii-2013",
          },
          {
            sequence: 987,
            prettyDate: "Sat Jan 16, 2021",
            gradeValue: 2.33,
            title: "Victor Crowley",
            year: 2017,
            slug: "victor-crowley-2017",
          },
          {
            sequence: 1086,
            prettyDate: "Mon Apr 19, 2021",
            gradeValue: 5,
            title: "California Split",
            year: 1974,
            slug: "california-split-1974",
          },
          {
            sequence: 1090,
            prettyDate: "Fri Apr 23, 2021",
            gradeValue: 2.33,
            title: "Friday the 13th Part VII: The New Blood",
            year: 1988,
            slug: "friday-the-13th-part-vii-the-new-blood-1988",
          },
        ],
      },
      {
        fullName: "Hugh Jackman",
        slug: null,
        reviewCount: 8,
        averageGradeValue: 3.0824999999999996,
        reviews: [
          {
            sequence: 978,
            prettyDate: "Sat Jan 9, 2021",
            gradeValue: 4,
            title: "X-Men",
            year: 2000,
            slug: "x-men-2000",
          },
          {
            sequence: 986,
            prettyDate: "Sat Jan 16, 2021",
            gradeValue: 3,
            title: "X2: X-Men United",
            year: 2003,
            slug: "x2-x-men-united-2003",
          },
          {
            sequence: 995,
            prettyDate: "Sat Jan 23, 2021",
            gradeValue: 1,
            title: "X-Men: The Last Stand",
            year: 2006,
            slug: "x-men-the-last-stand-2006",
          },
          {
            sequence: 1002,
            prettyDate: "Sat Jan 30, 2021",
            gradeValue: 2,
            title: "X-Men Origins: Wolverine",
            year: 2009,
            slug: "x-men-origins-wolverine-2009",
          },
          {
            sequence: 1010,
            prettyDate: "Sat Feb 6, 2021",
            gradeValue: 4,
            title: "X-Men: First Class",
            year: 2011,
            slug: "x-men-first-class-2011",
          },
          {
            sequence: 1017,
            prettyDate: "Sat Feb 13, 2021",
            gradeValue: 3.33,
            title: "The Wolverine",
            year: 2013,
            slug: "the-wolverine-2013",
          },
          {
            sequence: 1024,
            prettyDate: "Sat Feb 20, 2021",
            gradeValue: 3.33,
            title: "X-Men: Days of Future Past",
            year: 2014,
            slug: "x-men-days-of-future-past-2014",
          },
          {
            sequence: 1048,
            prettyDate: "Sat Mar 13, 2021",
            gradeValue: 4,
            title: "Logan",
            year: 2017,
            slug: "logan-2017",
          },
        ],
      },
      {
        fullName: "Famke Janssen",
        slug: null,
        reviewCount: 6,
        averageGradeValue: 3.0549999999999997,
        reviews: [
          {
            sequence: 850,
            prettyDate: "Tue Aug 4, 2020",
            gradeValue: 3.67,
            title: "GoldenEye",
            year: 1995,
            slug: "goldeneye-1995",
          },
          {
            sequence: 978,
            prettyDate: "Sat Jan 9, 2021",
            gradeValue: 4,
            title: "X-Men",
            year: 2000,
            slug: "x-men-2000",
          },
          {
            sequence: 986,
            prettyDate: "Sat Jan 16, 2021",
            gradeValue: 3,
            title: "X2: X-Men United",
            year: 2003,
            slug: "x2-x-men-united-2003",
          },
          {
            sequence: 995,
            prettyDate: "Sat Jan 23, 2021",
            gradeValue: 1,
            title: "X-Men: The Last Stand",
            year: 2006,
            slug: "x-men-the-last-stand-2006",
          },
          {
            sequence: 1017,
            prettyDate: "Sat Feb 13, 2021",
            gradeValue: 3.33,
            title: "The Wolverine",
            year: 2013,
            slug: "the-wolverine-2013",
          },
          {
            sequence: 1024,
            prettyDate: "Sat Feb 20, 2021",
            gradeValue: 3.33,
            title: "X-Men: Days of Future Past",
            year: 2014,
            slug: "x-men-days-of-future-past-2014",
          },
        ],
      },
      {
        fullName: "John Wayne",
        slug: "john-wayne",
        reviewCount: 5,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 863,
            prettyDate: "Sat Aug 29, 2020",
            gradeValue: 3.67,
            title: "The Big Trail",
            year: 1930,
            slug: "the-big-trail-1930",
          },
          {
            sequence: 991,
            prettyDate: "Wed Jan 20, 2021",
            gradeValue: 2.67,
            title: "Arizona",
            year: 1931,
            slug: "arizona-1931",
          },
          {
            sequence: 1001,
            prettyDate: "Fri Jan 29, 2021",
            gradeValue: 5.33,
            title: "Rio Bravo",
            year: 1959,
            slug: "rio-bravo-1959",
          },
          {
            sequence: 1045,
            prettyDate: "Fri Mar 12, 2021",
            gradeValue: 2.33,
            title: "The Range Feud",
            year: 1931,
            slug: "the-range-feud-1931",
          },
          {
            sequence: 1051,
            prettyDate: "Tue Mar 16, 2021",
            gradeValue: 1,
            title: "Maker of Men",
            year: 1931,
            slug: "maker-of-men-1931",
          },
        ],
      },
      {
        fullName: "William Powell",
        slug: "william-powell",
        reviewCount: 14,
        averageGradeValue: 2.8564285714285718,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 845,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 3,
            title: "Charming Sinners",
            year: 1929,
            slug: "charming-sinners-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 849,
            prettyDate: "Sun Aug 2, 2020",
            gradeValue: 2,
            title: "Pointed Heels",
            year: 1929,
            slug: "pointed-heels-1929",
          },
          {
            sequence: 858,
            prettyDate: "Sat Aug 22, 2020",
            gradeValue: 3.33,
            title: "Behind the Make-Up",
            year: 1930,
            slug: "behind-the-make-up-1930",
          },
          {
            sequence: 859,
            prettyDate: "Sat Aug 22, 2020",
            gradeValue: 2.33,
            title: "Interference",
            year: 1928,
            slug: "interference-1928",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
          {
            sequence: 870,
            prettyDate: "Sun Sep 13, 2020",
            gradeValue: 3,
            title: "For the Defense",
            year: 1930,
            slug: "for-the-defense-1930",
          },
          {
            sequence: 877,
            prettyDate: "Wed Sep 30, 2020",
            gradeValue: 3,
            title: "Street of Chance",
            year: 1930,
            slug: "street-of-chance-1930",
          },
          {
            sequence: 885,
            prettyDate: "Sat Oct 10, 2020",
            gradeValue: 3.33,
            title: "Shadow of the Law",
            year: 1930,
            slug: "shadow-of-the-law-1930",
          },
          {
            sequence: 925,
            prettyDate: "Wed Nov 25, 2020",
            gradeValue: 3,
            title: "Ladies' Man",
            year: 1931,
            slug: "ladies-man-1931",
          },
          {
            sequence: 980,
            prettyDate: "Sun Jan 10, 2021",
            gradeValue: 2.33,
            title: "Man of the World",
            year: 1931,
            slug: "man-of-the-world-1931",
          },
          {
            sequence: 1036,
            prettyDate: "Tue Mar 2, 2021",
            gradeValue: 3.67,
            title: "The Road to Singapore",
            year: 1931,
            slug: "the-road-to-singapore-1931",
          },
          {
            sequence: 1100,
            prettyDate: "Wed May 12, 2021",
            gradeValue: 2.67,
            title: "High Pressure",
            year: 1932,
            slug: "high-pressure-1932",
          },
        ],
      },
      {
        fullName: "Brad Dourif",
        slug: null,
        reviewCount: 7,
        averageGradeValue: 2.712857142857143,
        reviews: [
          {
            sequence: 1052,
            prettyDate: "Wed Mar 17, 2021",
            gradeValue: 2.67,
            title: "Child's Play",
            year: 1988,
            slug: "childs-play-1988",
          },
          {
            sequence: 1072,
            prettyDate: "Sun Apr 4, 2021",
            gradeValue: 2.33,
            title: "Child's Play 2",
            year: 1990,
            slug: "childs-play-2-1990",
          },
          {
            sequence: 1078,
            prettyDate: "Sun Apr 11, 2021",
            gradeValue: 2.33,
            title: "Child's Play 3",
            year: 1991,
            slug: "childs-play-3-1991",
          },
          {
            sequence: 1085,
            prettyDate: "Sun Apr 18, 2021",
            gradeValue: 2.67,
            title: "Bride of Chucky",
            year: 1998,
            slug: "bride-of-chucky-1998",
          },
          {
            sequence: 1092,
            prettyDate: "Sun Apr 25, 2021",
            gradeValue: 3.33,
            title: "Seed of Chucky",
            year: 2004,
            slug: "seed-of-chucky-2004",
          },
          {
            sequence: 1105,
            prettyDate: "Sun May 16, 2021",
            gradeValue: 3.33,
            title: "Curse of Chucky",
            year: 2013,
            slug: "curse-of-chucky-2013",
          },
          {
            sequence: 1110,
            prettyDate: "Thu Jun 3, 2021",
            gradeValue: 2.33,
            title: "Cult of Chucky",
            year: 2017,
            slug: "cult-of-chucky-2017",
          },
        ],
      },
      {
        fullName: "Birger Malmsten",
        slug: null,
        reviewCount: 8,
        averageGradeValue: 2.665,
        reviews: [
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            gradeValue: 4,
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 952,
            prettyDate: "Sun Dec 20, 2020",
            gradeValue: 2.33,
            title: "A Ship to India",
            year: 1947,
            slug: "a-ship-to-india-1947",
          },
          {
            sequence: 976,
            prettyDate: "Fri Jan 8, 2021",
            gradeValue: 2.33,
            title: "Music in Darkness",
            year: 1948,
            slug: "music-in-darkness-1948",
          },
          {
            sequence: 1004,
            prettyDate: "Mon Feb 1, 2021",
            gradeValue: 2.33,
            title: "Prison",
            year: 1949,
            slug: "prison-1949",
          },
          {
            sequence: 1021,
            prettyDate: "Wed Feb 17, 2021",
            gradeValue: 1,
            title: "Thirst",
            year: 1949,
            slug: "thirst-1949",
          },
          {
            sequence: 1035,
            prettyDate: "Mon Mar 1, 2021",
            gradeValue: 3.33,
            title: "To Joy",
            year: 1950,
            slug: "to-joy-1950",
          },
          {
            sequence: 1058,
            prettyDate: "Wed Mar 24, 2021",
            gradeValue: 3.33,
            title: "Summer Interlude",
            year: 1951,
            slug: "summer-interlude-1951",
          },
          {
            sequence: 1069,
            prettyDate: "Thu Apr 1, 2021",
            gradeValue: 2.67,
            title: "Kvinnors väntan",
            year: 1952,
            slug: "waiting-women-1952",
          },
        ],
      },
      {
        fullName: "Boris Karloff",
        slug: "boris-karloff",
        reviewCount: 11,
        averageGradeValue: 2.6045454545454545,
        reviews: [
          {
            sequence: 837,
            prettyDate: "Thu Jul 9, 2020",
            gradeValue: 2.33,
            title: "Behind That Curtain",
            year: 1929,
            slug: "behind-that-curtain-1929",
          },
          {
            sequence: 889,
            prettyDate: "Sun Oct 11, 2020",
            gradeValue: 2,
            title: "Cracked Nuts",
            year: 1931,
            slug: "cracked-nuts-1931",
          },
          {
            sequence: 895,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 2.33,
            title: "The Sea Bat",
            year: 1930,
            slug: "the-sea-bat-1930",
          },
          {
            sequence: 919,
            prettyDate: "Wed Nov 18, 2020",
            gradeValue: 3.33,
            title: "The Criminal Code",
            year: 1930,
            slug: "the-criminal-code-1930",
          },
          {
            sequence: 984,
            prettyDate: "Thu Jan 14, 2021",
            gradeValue: 2.67,
            title: "The Utah Kid",
            year: 1930,
            slug: "the-utah-kid-1930",
          },
          {
            sequence: 1022,
            prettyDate: "Thu Feb 18, 2021",
            gradeValue: 3,
            title: "The Public Defender",
            year: 1931,
            slug: "the-public-defender-1931",
          },
          {
            sequence: 1030,
            prettyDate: "Thu Feb 25, 2021",
            gradeValue: 2.33,
            title: "Five Star Final",
            year: 1931,
            slug: "five-star-final-1931",
          },
          {
            sequence: 1031,
            prettyDate: "Fri Feb 26, 2021",
            gradeValue: 1,
            title: "I Like Your Nerve",
            year: 1931,
            slug: "i-like-your-nerve-1931",
          },
          {
            sequence: 1046,
            prettyDate: "Fri Mar 12, 2021",
            gradeValue: 3,
            title: "The Guilty Generation",
            year: 1931,
            slug: "the-guilty-generation-1931",
          },
          {
            sequence: 1087,
            prettyDate: "Tue Apr 20, 2021",
            gradeValue: 4.33,
            title: "Frankenstein",
            year: 1931,
            slug: "frankenstein-1931",
          },
          {
            sequence: 1097,
            prettyDate: "Mon May 3, 2021",
            gradeValue: 2.33,
            title: "Tonight or Never",
            year: 1931,
            slug: "tonight-or-never-1931",
          },
        ],
      },
      {
        fullName: "Bela Lugosi",
        slug: "bela-lugosi",
        reviewCount: 7,
        averageGradeValue: 2.5700000000000003,
        reviews: [
          {
            sequence: 854,
            prettyDate: "Mon Aug 17, 2020",
            gradeValue: 2.33,
            title: "The Thirteenth Chair",
            year: 1929,
            slug: "the-thirteenth-chair-1929",
          },
          {
            sequence: 880,
            prettyDate: "Sun Oct 4, 2020",
            gradeValue: 4.67,
            title: "Dracula",
            year: 1931,
            slug: "dracula-1931",
          },
          {
            sequence: 886,
            prettyDate: "Sat Oct 10, 2020",
            gradeValue: 3.33,
            title: "Renegades",
            year: 1930,
            slug: "renegades-1930",
          },
          {
            sequence: 922,
            prettyDate: "Tue Nov 24, 2020",
            gradeValue: 2.33,
            title: "Wild Company",
            year: 1930,
            slug: "wild-company-1930",
          },
          {
            sequence: 923,
            prettyDate: "Tue Nov 24, 2020",
            gradeValue: 1,
            title: "Oh, for a Man!",
            year: 1930,
            slug: "oh-for-a-man-1930",
          },
          {
            sequence: 926,
            prettyDate: "Thu Nov 26, 2020",
            gradeValue: 3.33,
            title: "The Black Camel",
            year: 1931,
            slug: "the-black-camel-1931",
          },
          {
            sequence: 1034,
            prettyDate: "Sun Feb 28, 2021",
            gradeValue: 1,
            title: "Broadminded",
            year: 1931,
            slug: "broadminded-1931",
          },
        ],
      },
      {
        fullName: "Frank Albertson",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 2.5300000000000002,
        reviews: [
          {
            sequence: 867,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 2.33,
            title: "Born Reckless",
            year: 1930,
            slug: "born-reckless-1930",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 3.33,
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
          {
            sequence: 922,
            prettyDate: "Tue Nov 24, 2020",
            gradeValue: 2.33,
            title: "Wild Company",
            year: 1930,
            slug: "wild-company-1930",
          },
          {
            sequence: 1081,
            prettyDate: "Wed Apr 14, 2021",
            gradeValue: 2.33,
            title: "Way Back Home",
            year: 1931,
            slug: "way-back-home-1931",
          },
        ],
      },
      {
        fullName: "Richard Tucker",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 2.132,
        reviews: [
          {
            sequence: 855,
            prettyDate: "Tue Aug 18, 2020",
            gradeValue: 2.33,
            title: "The Unholy Night",
            year: 1929,
            slug: "the-unholy-night-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
          {
            sequence: 885,
            prettyDate: "Sat Oct 10, 2020",
            gradeValue: 3.33,
            title: "Shadow of the Law",
            year: 1930,
            slug: "shadow-of-the-law-1930",
          },
          {
            sequence: 928,
            prettyDate: "Fri Nov 27, 2020",
            gradeValue: 1,
            title: "A Holy Terror",
            year: 1931,
            slug: "a-holy-terror-1931",
          },
          {
            sequence: 1051,
            prettyDate: "Tue Mar 16, 2021",
            gradeValue: 1,
            title: "Maker of Men",
            year: 1931,
            slug: "maker-of-men-1931",
          },
        ],
      },
    ],
  },
  writers: {
    highestRated: [
      {
        fullName: "Christopher Markus",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 4.886666666666667,
        reviews: [
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            gradeValue: 4.33,
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            gradeValue: 5.33,
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            gradeValue: 5,
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Lucio Fulci",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 3.6,
        reviews: [
          {
            sequence: 873,
            prettyDate: "Mon Sep 21, 2020",
            gradeValue: 3.33,
            title: "Massacre Time",
            year: 1966,
            slug: "the-brute-and-the-beast-1966",
          },
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            gradeValue: 4,
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 3.67,
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            gradeValue: 3.33,
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            gradeValue: 3.67,
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
        ],
      },
      {
        fullName: "Garrett Fort",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3.5825,
        reviews: [
          {
            sequence: 880,
            prettyDate: "Sun Oct 4, 2020",
            gradeValue: 4.67,
            title: "Dracula",
            year: 1931,
            slug: "dracula-1931",
          },
          {
            sequence: 967,
            prettyDate: "Fri Jan 1, 2021",
            gradeValue: 2,
            title: "Outside the Law",
            year: 1930,
            slug: "outside-the-law-1930",
          },
          {
            sequence: 1066,
            prettyDate: "Sun Mar 28, 2021",
            gradeValue: 3.33,
            title: "Drácula",
            year: 1931,
            slug: "dracula-1931-spanish",
          },
          {
            sequence: 1087,
            prettyDate: "Tue Apr 20, 2021",
            gradeValue: 4.33,
            title: "Frankenstein",
            year: 1931,
            slug: "frankenstein-1931",
          },
        ],
      },
      {
        fullName: "Roberto Gianviti",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 3.4,
        reviews: [
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            gradeValue: 4,
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            gradeValue: 3.67,
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            gradeValue: 3.33,
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            gradeValue: 3.67,
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
          {
            sequence: 1060,
            prettyDate: "Fri Mar 26, 2021",
            gradeValue: 2.33,
            title: "White Fang",
            year: 1973,
            slug: "white-fang-1973",
          },
        ],
      },
      {
        fullName: "Ingmar Bergman",
        slug: null,
        reviewCount: 12,
        averageGradeValue: 3.248333333333333,
        reviews: [
          {
            sequence: 942,
            prettyDate: "Sun Dec 13, 2020",
            gradeValue: 3.67,
            title: "Crisis",
            year: 1946,
            slug: "crisis-1946",
          },
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            gradeValue: 4,
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 952,
            prettyDate: "Sun Dec 20, 2020",
            gradeValue: 2.33,
            title: "A Ship to India",
            year: 1947,
            slug: "a-ship-to-india-1947",
          },
          {
            sequence: 981,
            prettyDate: "Mon Jan 11, 2021",
            gradeValue: 2.33,
            title: "Port of Call",
            year: 1948,
            slug: "port-of-call-1948",
          },
          {
            sequence: 1004,
            prettyDate: "Mon Feb 1, 2021",
            gradeValue: 2.33,
            title: "Prison",
            year: 1949,
            slug: "prison-1949",
          },
          {
            sequence: 1035,
            prettyDate: "Mon Mar 1, 2021",
            gradeValue: 3.33,
            title: "To Joy",
            year: 1950,
            slug: "to-joy-1950",
          },
          {
            sequence: 1058,
            prettyDate: "Wed Mar 24, 2021",
            gradeValue: 3.33,
            title: "Summer Interlude",
            year: 1951,
            slug: "summer-interlude-1951",
          },
          {
            sequence: 1069,
            prettyDate: "Thu Apr 1, 2021",
            gradeValue: 2.67,
            title: "Kvinnors väntan",
            year: 1952,
            slug: "waiting-women-1952",
          },
          {
            sequence: 1079,
            prettyDate: "Mon Apr 12, 2021",
            gradeValue: 4.33,
            title: "Summer with Monika",
            year: 1953,
            slug: "summer-with-monika-1953",
          },
          {
            sequence: 1089,
            prettyDate: "Thu Apr 22, 2021",
            gradeValue: 4.33,
            title: "Sawdust and Tinsel",
            year: 1953,
            slug: "sawdust-and-tinsel-1953",
          },
          {
            sequence: 1094,
            prettyDate: "Wed Apr 28, 2021",
            gradeValue: 3,
            title: "A Lesson in Love",
            year: 1954,
            slug: "a-lesson-in-love-1954",
          },
          {
            sequence: 1098,
            prettyDate: "Tue May 4, 2021",
            gradeValue: 3.33,
            title: "Dreams",
            year: 1955,
            slug: "dreams-1955",
          },
        ],
      },
      {
        fullName: "Val Guest",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            gradeValue: 3.67,
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            gradeValue: 2.33,
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            gradeValue: 2.33,
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
          {
            sequence: 915,
            prettyDate: "Tue Nov 10, 2020",
            gradeValue: 3.67,
            title: "The Camp on Blood Island",
            year: 1958,
            slug: "the-camp-on-blood-island-1958",
          },
        ],
      },
      {
        fullName: "Bryan Singer",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 3,
        reviews: [
          {
            sequence: 978,
            prettyDate: "Sat Jan 9, 2021",
            gradeValue: 4,
            title: "X-Men",
            year: 2000,
            slug: "x-men-2000",
          },
          {
            sequence: 986,
            prettyDate: "Sat Jan 16, 2021",
            gradeValue: 3,
            title: "X2: X-Men United",
            year: 2003,
            slug: "x2-x-men-united-2003",
          },
          {
            sequence: 1010,
            prettyDate: "Sat Feb 6, 2021",
            gradeValue: 4,
            title: "X-Men: First Class",
            year: 2011,
            slug: "x-men-first-class-2011",
          },
          {
            sequence: 1040,
            prettyDate: "Sat Mar 6, 2021",
            gradeValue: 1,
            title: "X-Men: Apocalypse",
            year: 2016,
            slug: "x-men-apocalypse-2016",
          },
        ],
      },
      {
        fullName: "Adam Green",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2.8325,
        reviews: [
          {
            sequence: 871,
            prettyDate: "Sat Sep 19, 2020",
            gradeValue: 3,
            title: "Hatchet",
            year: 2006,
            slug: "hatchet-2006",
          },
          {
            sequence: 890,
            prettyDate: "Thu Oct 15, 2020",
            gradeValue: 2.67,
            title: "Hatchet II",
            year: 2010,
            slug: "hatchet-ii-2010",
          },
          {
            sequence: 920,
            prettyDate: "Thu Nov 19, 2020",
            gradeValue: 3.33,
            title: "Hatchet III",
            year: 2013,
            slug: "hatchet-iii-2013",
          },
          {
            sequence: 987,
            prettyDate: "Sat Jan 16, 2021",
            gradeValue: 2.33,
            title: "Victor Crowley",
            year: 2017,
            slug: "victor-crowley-2017",
          },
        ],
      },
      {
        fullName: "Dudley Nichols",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2.83,
        reviews: [
          {
            sequence: 867,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 2.33,
            title: "Born Reckless",
            year: 1930,
            slug: "born-reckless-1930",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 3.33,
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 926,
            prettyDate: "Thu Nov 26, 2020",
            gradeValue: 3.33,
            title: "The Black Camel",
            year: 1931,
            slug: "the-black-camel-1931",
          },
          {
            sequence: 975,
            prettyDate: "Thu Jan 7, 2021",
            gradeValue: 2.33,
            title: "Seas Beneath",
            year: 1931,
            slug: "seas-beneath-1931",
          },
        ],
      },
      {
        fullName: "Herman J. Mankiewicz",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.776666666666667,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 925,
            prettyDate: "Wed Nov 25, 2020",
            gradeValue: 3,
            title: "Ladies' Man",
            year: 1931,
            slug: "ladies-man-1931",
          },
          {
            sequence: 980,
            prettyDate: "Sun Jan 10, 2021",
            gradeValue: 2.33,
            title: "Man of the World",
            year: 1931,
            slug: "man-of-the-world-1931",
          },
        ],
      },
      {
        fullName: "S.S. Van Dine",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.776666666666667,
        reviews: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            gradeValue: 3,
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            gradeValue: 2.33,
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            gradeValue: 3,
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
        ],
      },
      {
        fullName: "Brian De Palma",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 2.732,
        reviews: [
          {
            sequence: 969,
            prettyDate: "Fri Jan 1, 2021",
            gradeValue: 3.67,
            title: "Murder à la Mod",
            year: 1968,
            slug: "murder-a-la-mod-1968",
          },
          {
            sequence: 1006,
            prettyDate: "Wed Feb 3, 2021",
            gradeValue: 2,
            title: "Greetings",
            year: 1968,
            slug: "greetings-1968",
          },
          {
            sequence: 1038,
            prettyDate: "Thu Mar 4, 2021",
            gradeValue: 2.33,
            title: "The Wedding Party",
            year: 1969,
            slug: "the-wedding-party-1969",
          },
          {
            sequence: 1068,
            prettyDate: "Wed Mar 31, 2021",
            gradeValue: 2.33,
            title: "Hi, Mom!",
            year: 1970,
            slug: "hi-mom-1970",
          },
          {
            sequence: 1095,
            prettyDate: "Thu Apr 29, 2021",
            gradeValue: 3.33,
            title: "Sisters",
            year: 1972,
            slug: "sisters-1972",
          },
        ],
      },
      {
        fullName: "Don Mancini",
        slug: null,
        reviewCount: 7,
        averageGradeValue: 2.712857142857143,
        reviews: [
          {
            sequence: 1052,
            prettyDate: "Wed Mar 17, 2021",
            gradeValue: 2.67,
            title: "Child's Play",
            year: 1988,
            slug: "childs-play-1988",
          },
          {
            sequence: 1072,
            prettyDate: "Sun Apr 4, 2021",
            gradeValue: 2.33,
            title: "Child's Play 2",
            year: 1990,
            slug: "childs-play-2-1990",
          },
          {
            sequence: 1078,
            prettyDate: "Sun Apr 11, 2021",
            gradeValue: 2.33,
            title: "Child's Play 3",
            year: 1991,
            slug: "childs-play-3-1991",
          },
          {
            sequence: 1085,
            prettyDate: "Sun Apr 18, 2021",
            gradeValue: 2.67,
            title: "Bride of Chucky",
            year: 1998,
            slug: "bride-of-chucky-1998",
          },
          {
            sequence: 1092,
            prettyDate: "Sun Apr 25, 2021",
            gradeValue: 3.33,
            title: "Seed of Chucky",
            year: 2004,
            slug: "seed-of-chucky-2004",
          },
          {
            sequence: 1105,
            prettyDate: "Sun May 16, 2021",
            gradeValue: 3.33,
            title: "Curse of Chucky",
            year: 2013,
            slug: "curse-of-chucky-2013",
          },
          {
            sequence: 1110,
            prettyDate: "Thu Jun 3, 2021",
            gradeValue: 2.33,
            title: "Cult of Chucky",
            year: 2017,
            slug: "cult-of-chucky-2017",
          },
        ],
      },
      {
        fullName: "David Cronenberg",
        slug: "david-cronenberg",
        reviewCount: 4,
        averageGradeValue: 2.4175,
        reviews: [
          {
            sequence: 964,
            prettyDate: "Sat Dec 26, 2020",
            gradeValue: 2,
            title: "Stereo (Tile 3B of a CAEE Educational Mosaic)",
            year: 1969,
            slug: "stereo-tile-3b-of-a-caee-educational-mosaic-1969",
          },
          {
            sequence: 972,
            prettyDate: "Sun Jan 3, 2021",
            gradeValue: 2.33,
            title: "Crimes of the Future",
            year: 1970,
            slug: "crimes-of-the-future-1970",
          },
          {
            sequence: 1000,
            prettyDate: "Thu Jan 28, 2021",
            gradeValue: 2.67,
            title: "Shivers",
            year: 1975,
            slug: "shivers-1975",
          },
          {
            sequence: 1007,
            prettyDate: "Thu Feb 4, 2021",
            gradeValue: 2.67,
            title: "Rabid",
            year: 1977,
            slug: "rabid-1977",
          },
        ],
      },
      {
        fullName: "Herbert Grevenius",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2.3325,
        reviews: [
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            gradeValue: 4,
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 1021,
            prettyDate: "Wed Feb 17, 2021",
            gradeValue: 1,
            title: "Thirst",
            year: 1949,
            slug: "thirst-1949",
          },
          {
            sequence: 1050,
            prettyDate: "Mon Mar 15, 2021",
            gradeValue: 1,
            title: "This Can't Happen Here",
            year: 1950,
            slug: "this-cant-happen-here-1950",
          },
          {
            sequence: 1058,
            prettyDate: "Wed Mar 24, 2021",
            gradeValue: 3.33,
            title: "Summer Interlude",
            year: 1951,
            slug: "summer-interlude-1951",
          },
        ],
      },
      {
        fullName: "Alfred Hitchcock",
        slug: null,
        reviewCount: 5,
        averageGradeValue: 2.266,
        reviews: [
          {
            sequence: 838,
            prettyDate: "Fri Jul 10, 2020",
            gradeValue: 3.33,
            title: "Blackmail",
            year: 1929,
            slug: "blackmail-1929",
          },
          {
            sequence: 876,
            prettyDate: "Mon Sep 28, 2020",
            gradeValue: 3,
            title: "Murder!",
            year: 1930,
            slug: "murder-1930",
          },
          {
            sequence: 909,
            prettyDate: "Mon Nov 2, 2020",
            gradeValue: 1,
            title: "Juno and the Paycock",
            year: 1930,
            slug: "juno-and-the-paycock-1930",
          },
          {
            sequence: 979,
            prettyDate: "Sat Jan 9, 2021",
            gradeValue: 2,
            title: "The Skin Game",
            year: 1931,
            slug: "the-skin-game-1931",
          },
          {
            sequence: 1093,
            prettyDate: "Tue Apr 27, 2021",
            gradeValue: 2,
            title: "East of Shanghai",
            year: 1931,
            slug: "east-of-shanghai-1931",
          },
        ],
      },
      {
        fullName: "James Kevin McGuinness",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 2.22,
        reviews: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            gradeValue: 1,
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            gradeValue: 3.33,
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
        ],
      },
      {
        fullName: "Alma Reville",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 2,
        reviews: [
          {
            sequence: 876,
            prettyDate: "Mon Sep 28, 2020",
            gradeValue: 3,
            title: "Murder!",
            year: 1930,
            slug: "murder-1930",
          },
          {
            sequence: 909,
            prettyDate: "Mon Nov 2, 2020",
            gradeValue: 1,
            title: "Juno and the Paycock",
            year: 1930,
            slug: "juno-and-the-paycock-1930",
          },
          {
            sequence: 979,
            prettyDate: "Sat Jan 9, 2021",
            gradeValue: 2,
            title: "The Skin Game",
            year: 1931,
            slug: "the-skin-game-1931",
          },
          {
            sequence: 1093,
            prettyDate: "Tue Apr 27, 2021",
            gradeValue: 2,
            title: "East of Shanghai",
            year: 1931,
            slug: "east-of-shanghai-1931",
          },
        ],
      },
      {
        fullName: "Simon Kinberg",
        slug: null,
        reviewCount: 4,
        averageGradeValue: 1.915,
        reviews: [
          {
            sequence: 995,
            prettyDate: "Sat Jan 23, 2021",
            gradeValue: 1,
            title: "X-Men: The Last Stand",
            year: 2006,
            slug: "x-men-the-last-stand-2006",
          },
          {
            sequence: 1024,
            prettyDate: "Sat Feb 20, 2021",
            gradeValue: 3.33,
            title: "X-Men: Days of Future Past",
            year: 2014,
            slug: "x-men-days-of-future-past-2014",
          },
          {
            sequence: 1040,
            prettyDate: "Sat Mar 6, 2021",
            gradeValue: 1,
            title: "X-Men: Apocalypse",
            year: 2016,
            slug: "x-men-apocalypse-2016",
          },
          {
            sequence: 1071,
            prettyDate: "Sat Apr 3, 2021",
            gradeValue: 2.33,
            title: "X-Men: Dark Phoenix",
            year: 2019,
            slug: "x-men-dark-phoenix-2019",
          },
        ],
      },
      {
        fullName: "John Stone",
        slug: null,
        reviewCount: 3,
        averageGradeValue: 1.8866666666666667,
        reviews: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            gradeValue: 1,
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            gradeValue: 2.33,
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
          {
            sequence: 922,
            prettyDate: "Tue Nov 24, 2020",
            gradeValue: 2.33,
            title: "Wild Company",
            year: 1930,
            slug: "wild-company-1930",
          },
        ],
      },
    ],
  },
  year: {
    nodes: [
      {
        year: "all",
      },
      {
        year: "2021",
      },
      {
        year: "2020",
      },
    ],
  },
};
