export enum SchemaNames {
  HIGHEST_RATED_DIRECTORS_JSON = "HighestRatedDirectorsJson",
  HIGHEST_RATED_PERFORMERS_JSON = "HighestRatedPerformersJson",
  HIGHEST_RATED_PERSON = "HighestRatedPerson",
  HIGHEST_RATED_PERSON_REVIEW = "HighestRatedPersonReview",
  HIGHEST_RATED_WRITERS_JSON = "HighestRatedWritersJson",
  MARKDOWN_REMARK = "MarkdownRemark",
  MOST_WATCHED_DIRECTORS_JSON = "MostWatchedDirectorsJson",
  MOST_WATCHED_MOVIE = "MostWatchedMovie",
  MOST_WATCHED_MOVIE_VIEWING = "MostWatchedMovieViewing",
  MOST_WATCHED_MOVIES_JSON = "MostWatchedMoviesJson",
  MOST_WATCHED_PERFORMERS_JSON = "MostWatchedPerformersJson",
  MOST_WATCHED_PERSON = "MostWatchedPerson",
  MOST_WATCHED_PERSON_VIEWING = "MostWatchedPersonViewing",
  MOST_WATCHED_WRITERS_JSON = "MostWatchedWritersJson",
  OVERRATED_DISAPPOINTMENTS_JSON = "OverratedDisappointmentsJson",
  REVIEWED_MOVIES_JSON = "ReviewedMoviesJson",
  REVIEWED_MOVIES_WATCHLIST_ENTITIES = "ReviewedMoviesWatchlistEntities",
  TOP_VENUES_JSON = "TopVenuesJson",
  UNDERSEEN_GEMS_JSON = "UnderseenGemsJson",
  VENUE_STAT = "VenueStat",
  VIEWINGS_JSON = "ViewingsJson",
  WATCHLIST_ENTITIES_JSON = "WatchlistEntitiesJson",
  WATCHLIST_MOVIES_JSON = "WatchlistMoviesJson",
}
