export const data = {
  watchlistProgress: {
    reviewed: 346,
    total: 3618,
    directorTotal: 1258,
    directorReviewed: 132,
    directorDetails: [
      {
        name: "Abel Ferrara",
        reviewCount: 1,
        titleCount: 24,
        slug: "abel-ferrara",
      },
      {
        name: "Akira Kurosawa",
        reviewCount: 0,
        titleCount: 31,
        slug: null,
      },
      {
        name: "Alfred Hitchcock",
        reviewCount: 5,
        titleCount: 46,
        slug: "alfred-hitchcock",
      },
      {
        name: "Billy Wilder",
        reviewCount: 2,
        titleCount: 26,
        slug: "billy-wilder",
      },
      {
        name: "Brian De Palma",
        reviewCount: 16,
        titleCount: 30,
        slug: "brian-de-palma",
      },
      {
        name: "Dario Argento",
        reviewCount: 4,
        titleCount: 21,
        slug: "dario-argento",
      },
      {
        name: "David Cronenberg",
        reviewCount: 7,
        titleCount: 24,
        slug: "david-cronenberg",
      },
      {
        name: "David Lean",
        reviewCount: 1,
        titleCount: 16,
        slug: "david-lean",
      },
      {
        name: "François Truffaut",
        reviewCount: 0,
        titleCount: 23,
        slug: null,
      },
      {
        name: "Fritz Lang",
        reviewCount: 3,
        titleCount: 29,
        slug: "fritz-lang",
      },
      {
        name: "George A. Romero",
        reviewCount: 0,
        titleCount: 18,
        slug: null,
      },
      {
        name: "Howard Hawks",
        reviewCount: 5,
        titleCount: 33,
        slug: "howard-hawks",
      },
      {
        name: "Ingmar Bergman",
        reviewCount: 21,
        titleCount: 57,
        slug: "ingmar-bergman",
      },
      {
        name: "John Boorman",
        reviewCount: 1,
        titleCount: 18,
        slug: "john-boorman",
      },
      {
        name: "John Carpenter",
        reviewCount: 3,
        titleCount: 21,
        slug: "john-carpenter",
      },
      {
        name: "John Ford",
        reviewCount: 12,
        titleCount: 63,
        slug: "john-ford",
      },
      {
        name: "John Frankenheimer",
        reviewCount: 2,
        titleCount: 33,
        slug: "john-frankenheimer",
      },
      {
        name: "John Huston",
        reviewCount: 0,
        titleCount: 41,
        slug: null,
      },
      {
        name: "John Sturges",
        reviewCount: 3,
        titleCount: 44,
        slug: "john-sturges",
      },
      {
        name: "Ken Russell",
        reviewCount: 1,
        titleCount: 35,
        slug: "ken-russell",
      },
      {
        name: "Lucio Fulci",
        reviewCount: 10,
        titleCount: 33,
        slug: "lucio-fulci",
      },
      {
        name: "Luis Buñuel",
        reviewCount: 1,
        titleCount: 31,
        slug: "luis-bunuel",
      },
      {
        name: "Mario Bava",
        reviewCount: 2,
        titleCount: 31,
        slug: "mario-bava",
      },
      {
        name: "Martin Scorsese",
        reviewCount: 0,
        titleCount: 28,
        slug: null,
      },
      {
        name: "Michael Haneke",
        reviewCount: 5,
        titleCount: 20,
        slug: "michael-haneke",
      },
      {
        name: "Michele Soavi",
        reviewCount: 1,
        titleCount: 18,
        slug: "michele-soavi",
      },
      {
        name: "Mike Nichols",
        reviewCount: 0,
        titleCount: 20,
        slug: null,
      },
      {
        name: "Orson Welles",
        reviewCount: 0,
        titleCount: 26,
        slug: null,
      },
      {
        name: "Paul Mazursky",
        reviewCount: 0,
        titleCount: 17,
        slug: null,
      },
      {
        name: "Paul Thomas Anderson",
        reviewCount: 1,
        titleCount: 9,
        slug: "paul-thomas-anderson",
      },
      {
        name: "Paul Verhoeven",
        reviewCount: 0,
        titleCount: 18,
        slug: null,
      },
      {
        name: "Quentin Tarantino",
        reviewCount: 0,
        titleCount: 14,
        slug: null,
      },
      {
        name: "Ridley Scott",
        reviewCount: 0,
        titleCount: 30,
        slug: null,
      },
      {
        name: "Robert Altman",
        reviewCount: 2,
        titleCount: 43,
        slug: "robert-altman",
      },
      {
        name: "Roger Corman",
        reviewCount: 1,
        titleCount: 56,
        slug: "roger-corman",
      },
      {
        name: "Roman Polanski",
        reviewCount: 1,
        titleCount: 25,
        slug: "roman-polanski",
      },
      {
        name: "Sam Peckinpah",
        reviewCount: 1,
        titleCount: 15,
        slug: "sam-peckinpah",
      },
      {
        name: "Sergio Leone",
        reviewCount: 0,
        titleCount: 8,
        slug: null,
      },
      {
        name: "Sidney Lumet",
        reviewCount: 1,
        titleCount: 50,
        slug: "sidney-lumet",
      },
      {
        name: "Stanley Kubrick",
        reviewCount: 1,
        titleCount: 13,
        slug: "stanley-kubrick",
      },
      {
        name: "The Coen Brothers",
        reviewCount: 0,
        titleCount: 19,
        slug: null,
      },
      {
        name: "Tobe Hooper",
        reviewCount: 1,
        titleCount: 19,
        slug: "tobe-hooper",
      },
      {
        name: "Tod Browning",
        reviewCount: 6,
        titleCount: 10,
        slug: "tod-browning",
      },
      {
        name: "Tony Scott",
        reviewCount: 1,
        titleCount: 17,
        slug: "tony-scott",
      },
      {
        name: "Wes Anderson",
        reviewCount: 0,
        titleCount: 11,
        slug: null,
      },
      {
        name: "Wes Craven",
        reviewCount: 7,
        titleCount: 25,
        slug: "wes-craven",
      },
      {
        name: "William Friedkin",
        reviewCount: 3,
        titleCount: 25,
        slug: "william-friedkin",
      },
    ],
    performerTotal: 2030,
    performerReviewed: 163,
    performerDetails: [
      {
        name: "Bela Lugosi",
        reviewCount: 10,
        titleCount: 65,
        slug: "bela-lugosi",
      },
      {
        name: "Bette Davis",
        reviewCount: 13,
        titleCount: 101,
        slug: "bette-davis",
      },
      {
        name: "Boris Karloff",
        reviewCount: 15,
        titleCount: 97,
        slug: "boris-karloff",
      },
      {
        name: "Burt Reynolds",
        reviewCount: 2,
        titleCount: 113,
        slug: "burt-reynolds",
      },
      {
        name: "Cary Grant",
        reviewCount: 6,
        titleCount: 72,
        slug: "cary-grant",
      },
      {
        name: "Christopher Lee",
        reviewCount: 6,
        titleCount: 196,
        slug: "christopher-lee",
      },
      {
        name: "Dean Martin",
        reviewCount: 1,
        titleCount: 38,
        slug: "dean-martin",
      },
      {
        name: "Errol Flynn",
        reviewCount: 2,
        titleCount: 54,
        slug: "errol-flynn",
      },
      {
        name: "Frank Sinatra",
        reviewCount: 2,
        titleCount: 53,
        slug: "frank-sinatra",
      },
      {
        name: "Gene Hackman",
        reviewCount: 2,
        titleCount: 79,
        slug: "gene-hackman",
      },
      {
        name: "Humphrey Bogart",
        reviewCount: 26,
        titleCount: 75,
        slug: "humphrey-bogart",
      },
      {
        name: "Jack Lemmon",
        reviewCount: 3,
        titleCount: 65,
        slug: "jack-lemmon",
      },
      {
        name: "Jack Nicholson",
        reviewCount: 3,
        titleCount: 61,
        slug: "jack-nicholson",
      },
      {
        name: "James Coburn",
        reviewCount: 5,
        titleCount: 84,
        slug: "james-coburn",
      },
      {
        name: "James Garner",
        reviewCount: 0,
        titleCount: 68,
        slug: null,
      },
      {
        name: "James Stewart",
        reviewCount: 2,
        titleCount: 81,
        slug: "james-stewart",
      },
      {
        name: "John Wayne",
        reviewCount: 16,
        titleCount: 146,
        slug: "john-wayne",
      },
      {
        name: "Lee Marvin",
        reviewCount: 2,
        titleCount: 53,
        slug: "lee-marvin",
      },
      {
        name: "Marilyn Monroe",
        reviewCount: 1,
        titleCount: 26,
        slug: "marilyn-monroe",
      },
      {
        name: "Paul Newman",
        reviewCount: 0,
        titleCount: 57,
        slug: null,
      },
      {
        name: "Peter Cushing",
        reviewCount: 9,
        titleCount: 95,
        slug: "peter-cushing",
      },
      {
        name: "Robert Mitchum",
        reviewCount: 7,
        titleCount: 113,
        slug: "robert-mitchum",
      },
      {
        name: "Sean Connery",
        reviewCount: 0,
        titleCount: 69,
        slug: null,
      },
      {
        name: "Steve McQueen",
        reviewCount: 1,
        titleCount: 27,
        slug: "steve-mcqueen",
      },
      {
        name: "Vincent Price",
        reviewCount: 3,
        titleCount: 109,
        slug: "vincent-price",
      },
      {
        name: "Warren Oates",
        reviewCount: 5,
        titleCount: 49,
        slug: "warren-oates",
      },
      {
        name: "William Holden",
        reviewCount: 6,
        titleCount: 69,
        slug: "william-holden",
      },
      {
        name: "William Powell",
        reviewCount: 27,
        titleCount: 60,
        slug: "william-powell",
      },
    ],
    writerTotal: 2030,
    writerReviewed: 163,
    writerDetails: [
      {
        name: "Anthony Shaffer",
        reviewCount: 0,
        titleCount: 11,
        slug: null,
      },
      {
        name: "Clive Barker",
        reviewCount: 3,
        titleCount: 15,
        slug: "clive-barker",
      },
      {
        name: "David Mamet",
        reviewCount: 1,
        titleCount: 30,
        slug: "david-mamet",
      },
      {
        name: "Leigh Brackett",
        reviewCount: 1,
        titleCount: 12,
        slug: "leigh-brackett",
      },
      {
        name: "Neil LaBute",
        reviewCount: 1,
        titleCount: 15,
        slug: "neil-labute",
      },
      {
        name: "Raymond Chandler",
        reviewCount: 1,
        titleCount: 20,
        slug: "raymond-chandler",
      },
      {
        name: "Stephen King",
        reviewCount: 1,
        titleCount: 81,
        slug: "stephen-king",
      },
    ],
    collectionTotal: 408,
    collectionReviewed: 62,
    collectionDetails: [
      {
        name: "Child's Play",
        reviewCount: 8,
        titleCount: 8,
        slug: "childs-play",
      },
      {
        name: "Friday the 13th",
        reviewCount: 10,
        titleCount: 12,
        slug: "friday-the-13th",
      },
      {
        name: "Halloween",
        reviewCount: 6,
        titleCount: 13,
        slug: "halloween",
      },
      {
        name: "Hammer Films",
        reviewCount: 7,
        titleCount: 94,
        slug: "hammer-films",
      },
      {
        name: "Hatchet",
        reviewCount: 4,
        titleCount: 4,
        slug: "hatchet",
      },
      {
        name: "James Bond",
        reviewCount: 6,
        titleCount: 27,
        slug: "james-bond",
      },
      {
        name: "Phantasm",
        reviewCount: 5,
        titleCount: 5,
        slug: "phantasm",
      },
      {
        name: "Saw",
        reviewCount: 7,
        titleCount: 9,
        slug: "saw",
      },
      {
        name: "Shaw Brothers",
        reviewCount: 6,
        titleCount: 208,
        slug: "shaw-brothers",
      },
      {
        name: "Universal Monsters",
        reviewCount: 3,
        titleCount: 29,
        slug: "universal-monsters",
      },
    ],
  },
};
