export const data = {
  reviewedMovies: {
    totalCount: 287,
  },
  watchlistMovies: {
    totalCount: 3217,
  },
  director: {
    nodes: [
      {
        name: "Abel Ferrara",
        reviewCount: 1,
        titleCount: 22,
        slug: "abel-ferrara",
        entityType: "director" as const,
      },
      {
        name: "Akira Kurosawa",
        reviewCount: 1,
        titleCount: 32,
        slug: "akira-kurosawa",
        entityType: "director" as const,
      },
      {
        name: "Alfred Hitchcock",
        reviewCount: 5,
        titleCount: 44,
        slug: "alfred-hitchcock",
        entityType: "director" as const,
      },
      {
        name: "Billy Wilder",
        reviewCount: 2,
        titleCount: 26,
        slug: "billy-wilder",
        entityType: "director" as const,
      },
      {
        name: "Brian De Palma",
        reviewCount: 16,
        titleCount: 30,
        slug: "brian-de-palma",
        entityType: "director" as const,
      },
      {
        name: "Dario Argento",
        reviewCount: 4,
        titleCount: 20,
        slug: "dario-argento",
        entityType: "director" as const,
      },
      {
        name: "David Cronenberg",
        reviewCount: 6,
        titleCount: 23,
        slug: "david-cronenberg",
        entityType: "director" as const,
      },
      {
        name: "David Lean",
        reviewCount: 1,
        titleCount: 17,
        slug: "david-lean",
        entityType: "director" as const,
      },
      {
        name: "François Truffaut",
        reviewCount: 0,
        titleCount: 23,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Fritz Lang",
        reviewCount: 3,
        titleCount: 31,
        slug: "fritz-lang",
        entityType: "director" as const,
      },
      {
        name: "George A. Romero",
        reviewCount: 0,
        titleCount: 17,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Howard Hawks",
        reviewCount: 5,
        titleCount: 38,
        slug: "howard-hawks",
        entityType: "director" as const,
      },
      {
        name: "Ingmar Bergman",
        reviewCount: 21,
        titleCount: 38,
        slug: "ingmar-bergman",
        entityType: "director" as const,
      },
      {
        name: "The Coen Brothers",
        reviewCount: 0,
        titleCount: 21,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "John Boorman",
        reviewCount: 0,
        titleCount: 17,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "John Carpenter",
        reviewCount: 3,
        titleCount: 18,
        slug: "john-carpenter",
        entityType: "director" as const,
      },
      {
        name: "John Ford",
        reviewCount: 12,
        titleCount: 62,
        slug: "john-ford",
        entityType: "director" as const,
      },
      {
        name: "John Frankenheimer",
        reviewCount: 1,
        titleCount: 29,
        slug: "john-frankenheimer",
        entityType: "director" as const,
      },
      {
        name: "John Huston",
        reviewCount: 0,
        titleCount: 41,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "John Sturges",
        reviewCount: 1,
        titleCount: 43,
        slug: "john-sturges",
        entityType: "director" as const,
      },
      {
        name: "Ken Russell",
        reviewCount: 1,
        titleCount: 22,
        slug: "ken-russell",
        entityType: "director" as const,
      },
      {
        name: "Lucio Fulci",
        reviewCount: 8,
        titleCount: 28,
        slug: "lucio-fulci",
        entityType: "director" as const,
      },
      {
        name: "Luis Buñuel",
        reviewCount: 1,
        titleCount: 31,
        slug: "luis-bunuel",
        entityType: "director" as const,
      },
      {
        name: "Mario Bava",
        reviewCount: 2,
        titleCount: 31,
        slug: "mario-bava",
        entityType: "director" as const,
      },
      {
        name: "Martin Scorsese",
        reviewCount: 0,
        titleCount: 27,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Michael Haneke",
        reviewCount: 5,
        titleCount: 12,
        slug: "michael-haneke",
        entityType: "director" as const,
      },
      {
        name: "Michele Soavi",
        reviewCount: 1,
        titleCount: 7,
        slug: "michele-soavi",
        entityType: "director" as const,
      },
      {
        name: "Mike Nichols",
        reviewCount: 0,
        titleCount: 19,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Orson Welles",
        reviewCount: 0,
        titleCount: 18,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Paul Mazursky",
        reviewCount: 0,
        titleCount: 15,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Paul Thomas Anderson",
        reviewCount: 1,
        titleCount: 9,
        slug: "paul-thomas-anderson",
        entityType: "director" as const,
      },
      {
        name: "Paul Verhoeven",
        reviewCount: 0,
        titleCount: 17,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Quentin Tarantino",
        reviewCount: 0,
        titleCount: 14,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Ridley Scott",
        reviewCount: 0,
        titleCount: 28,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Robert Altman",
        reviewCount: 1,
        titleCount: 36,
        slug: "robert-altman",
        entityType: "director" as const,
      },
      {
        name: "Roger Corman",
        reviewCount: 1,
        titleCount: 56,
        slug: "roger-corman",
        entityType: "director" as const,
      },
      {
        name: "Roman Polanski",
        reviewCount: 1,
        titleCount: 23,
        slug: "roman-polanski",
        entityType: "director" as const,
      },
      {
        name: "Sam Peckinpah",
        reviewCount: 1,
        titleCount: 14,
        slug: "sam-peckinpah",
        entityType: "director" as const,
      },
      {
        name: "Sergio Leone",
        reviewCount: 0,
        titleCount: 7,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Sergio Martino",
        reviewCount: 1,
        titleCount: 15,
        slug: "sergio-martino",
        entityType: "director" as const,
      },
      {
        name: "Sidney Lumet",
        reviewCount: 0,
        titleCount: 43,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Stanley Kubrick",
        reviewCount: 1,
        titleCount: 13,
        slug: "stanley-kubrick",
        entityType: "director" as const,
      },
      {
        name: "Tobe Hooper",
        reviewCount: 1,
        titleCount: 15,
        slug: "tobe-hooper",
        entityType: "director" as const,
      },
      {
        name: "Tod Browning",
        reviewCount: 5,
        titleCount: 9,
        slug: "tod-browning",
        entityType: "director" as const,
      },
      {
        name: "Tony Scott",
        reviewCount: 1,
        titleCount: 17,
        slug: "tony-scott",
        entityType: "director" as const,
      },
      {
        name: "Wes Anderson",
        reviewCount: 0,
        titleCount: 10,
        slug: null,
        entityType: "director" as const,
      },
      {
        name: "Wes Craven",
        reviewCount: 6,
        titleCount: 21,
        slug: "wes-craven",
        entityType: "director" as const,
      },
      {
        name: "William Friedkin",
        reviewCount: 1,
        titleCount: 19,
        slug: "william-friedkin",
        entityType: "director" as const,
      },
    ],
  },
  directorTotal: {
    sum: 1168,
  },
  directorReviewed: {
    sum: 121,
  },
  performer: {
    nodes: [
      {
        name: "Bela Lugosi",
        reviewCount: 8,
        titleCount: 63,
        slug: "bela-lugosi",
        entityType: "performer" as const,
      },
      {
        name: "Ben Johnson",
        reviewCount: 0,
        titleCount: 55,
        slug: null,
        entityType: "performer" as const,
      },
      {
        name: "Bette Davis",
        reviewCount: 7,
        titleCount: 87,
        slug: "bette-davis",
        entityType: "performer" as const,
      },
      {
        name: "Boris Karloff",
        reviewCount: 18,
        titleCount: 98,
        slug: "boris-karloff",
        entityType: "performer" as const,
      },
      {
        name: "Burt Reynolds",
        reviewCount: 2,
        titleCount: 100,
        slug: "burt-reynolds",
        entityType: "performer" as const,
      },
      {
        name: "Cary Grant",
        reviewCount: 6,
        titleCount: 73,
        slug: "cary-grant",
        entityType: "performer" as const,
      },
      {
        name: "Christopher Lee",
        reviewCount: 4,
        titleCount: 184,
        slug: "christopher-lee",
        entityType: "performer" as const,
      },
      {
        name: "Dean Martin",
        reviewCount: 1,
        titleCount: 39,
        slug: "dean-martin",
        entityType: "performer" as const,
      },
      {
        name: "Errol Flynn",
        reviewCount: 2,
        titleCount: 54,
        slug: "errol-flynn",
        entityType: "performer" as const,
      },
      {
        name: "Frank Sinatra",
        reviewCount: 2,
        titleCount: 55,
        slug: "frank-sinatra",
        entityType: "performer" as const,
      },
      {
        name: "Gene Hackman",
        reviewCount: 1,
        titleCount: 78,
        slug: "gene-hackman",
        entityType: "performer" as const,
      },
      {
        name: "Humphrey Bogart",
        reviewCount: 12,
        titleCount: 73,
        slug: "humphrey-bogart",
        entityType: "performer" as const,
      },
      {
        name: "Jack Lemmon",
        reviewCount: 3,
        titleCount: 57,
        slug: "jack-lemmon",
        entityType: "performer" as const,
      },
      {
        name: "Jack Nicholson",
        reviewCount: 2,
        titleCount: 62,
        slug: "jack-nicholson",
        entityType: "performer" as const,
      },
      {
        name: "James Coburn",
        reviewCount: 2,
        titleCount: 67,
        slug: "james-coburn",
        entityType: "performer" as const,
      },
      {
        name: "James Garner",
        reviewCount: 0,
        titleCount: 49,
        slug: null,
        entityType: "performer" as const,
      },
      {
        name: "James Stewart",
        reviewCount: 1,
        titleCount: 79,
        slug: "james-stewart",
        entityType: "performer" as const,
      },
      {
        name: "John Wayne",
        reviewCount: 13,
        titleCount: 146,
        slug: "john-wayne",
        entityType: "performer" as const,
      },
      {
        name: "Lee Marvin",
        reviewCount: 0,
        titleCount: 51,
        slug: null,
        entityType: "performer" as const,
      },
      {
        name: "Marilyn Monroe",
        reviewCount: 1,
        titleCount: 26,
        slug: "marilyn-monroe",
        entityType: "performer" as const,
      },
      {
        name: "Paul Newman",
        reviewCount: 0,
        titleCount: 57,
        slug: null,
        entityType: "performer" as const,
      },
      {
        name: "Peter Cushing",
        reviewCount: 7,
        titleCount: 88,
        slug: "peter-cushing",
        entityType: "performer" as const,
      },
      {
        name: "Robert Mitchum",
        reviewCount: 5,
        titleCount: 107,
        slug: "robert-mitchum",
        entityType: "performer" as const,
      },
      {
        name: "Sean Connery",
        reviewCount: 0,
        titleCount: 68,
        slug: null,
        entityType: "performer" as const,
      },
      {
        name: "Steve McQueen",
        reviewCount: 0,
        titleCount: 27,
        slug: null,
        entityType: "performer" as const,
      },
      {
        name: "Tom Atkins",
        reviewCount: 0,
        titleCount: 26,
        slug: null,
        entityType: "performer" as const,
      },
      {
        name: "Vincent Price",
        reviewCount: 3,
        titleCount: 98,
        slug: "vincent-price",
        entityType: "performer" as const,
      },
      {
        name: "Warren Oates",
        reviewCount: 5,
        titleCount: 41,
        slug: "warren-oates",
        entityType: "performer" as const,
      },
      {
        name: "William Holden",
        reviewCount: 5,
        titleCount: 69,
        slug: "william-holden",
        entityType: "performer" as const,
      },
      {
        name: "William Powell",
        reviewCount: 17,
        titleCount: 60,
        slug: "william-powell",
        entityType: "performer" as const,
      },
    ],
  },
  performerTotal: {
    sum: 2137,
  },
  performerReviewed: {
    sum: 127,
  },
  writer: {
    nodes: [
      {
        name: "Anthony Shaffer",
        reviewCount: 0,
        titleCount: 12,
        slug: null,
        entityType: "writer" as const,
      },
      {
        name: "Clive Barker",
        reviewCount: 4,
        titleCount: 13,
        slug: "clive-barker",
        entityType: "writer" as const,
      },
      {
        name: "David Mamet",
        reviewCount: 1,
        titleCount: 26,
        slug: "david-mamet",
        entityType: "writer" as const,
      },
      {
        name: "Leigh Brackett",
        reviewCount: 1,
        titleCount: 12,
        slug: "leigh-brackett",
        entityType: "writer" as const,
      },
      {
        name: "Neil LaBute",
        reviewCount: 1,
        titleCount: 10,
        slug: "neil-labute",
        entityType: "writer" as const,
      },
      {
        name: "Raymond Chandler",
        reviewCount: 0,
        titleCount: 15,
        slug: null,
        entityType: "writer" as const,
      },
      {
        name: "Stephen King",
        reviewCount: 1,
        titleCount: 57,
        slug: "stephen-king",
        entityType: "writer" as const,
      },
    ],
  },
  writerTotal: {
    sum: 145,
  },
  writerReviewed: {
    sum: 8,
  },
  collection: {
    nodes: [
      {
        name: "Child's Play",
        reviewCount: 8,
        titleCount: 8,
        slug: "childs-play",
        entityType: "collection" as const,
      },
      {
        name: "Friday the 13th",
        reviewCount: 9,
        titleCount: 12,
        slug: "friday-the-13th",
        entityType: "collection" as const,
      },
      {
        name: "Halloween",
        reviewCount: 5,
        titleCount: 12,
        slug: "halloween",
        entityType: "collection" as const,
      },
      {
        name: "Hammer Films",
        reviewCount: 7,
        titleCount: 94,
        slug: "hammer-films",
        entityType: "collection" as const,
      },
      {
        name: "Hatchet",
        reviewCount: 4,
        titleCount: 4,
        slug: "hatchet",
        entityType: "collection" as const,
      },
      {
        name: "James Bond",
        reviewCount: 6,
        titleCount: 27,
        slug: "james-bond",
        entityType: "collection" as const,
      },
      {
        name: "Phantasm",
        reviewCount: 2,
        titleCount: 5,
        slug: "phantasm",
        entityType: "collection" as const,
      },
      {
        name: "Saw",
        reviewCount: 6,
        titleCount: 9,
        slug: "saw",
        entityType: "collection" as const,
      },
      {
        name: "Shaw Brothers",
        reviewCount: 4,
        titleCount: 4,
        slug: "shaw-brothers",
        entityType: "collection" as const,
      },
      {
        name: "Universal Monsters",
        reviewCount: 3,
        titleCount: 29,
        slug: "universal-monsters",
        entityType: "collection" as const,
      },
    ],
  },
  collectionTotal: {
    sum: 204,
  },
  collectionReviewed: {
    sum: 54,
  },
};
