export const checkboxLabelCss: string;
export const containerCss: string;
export const fromCss: string;
export const fromInputCss: string;
export const inputLabelCss: string;
export const legendCss: string;
export const toCss: string;
export const toInputCss: string;
export const wrapperCss: string;
