export enum SchemaNames {
  ViewingsJson = "ViewingsJson",
  AllTimeStatsJson = "AllTimeStatsJson",
  AllTimeStatsGradeDistribution = "AllTimeStatsGradeDistribution",
  StatsDistribution = "StatsDistribution",
  MostWatchedPerson = "MostWatchedPerson",
  MostWatchedPersonViewing = "MostWatchedPersonViewing",
  MostWatchedTitle = "MostWatchedTitle",
  YearStatsJson = "YearStatsJson",
  UnderseenGemsJson = "UnderseenGemsJson",
  OverratedDisappointmentsJson = "OverratedDisappointmentsJson",
  MarkdownRemark = "MarkdownRemark",
  ReviewedTitlesJson = "ReviewedTitlesJson",
  ReviewedTitleMore = "ReviewedTitleMore",
  ReviewedTitleMoreEntity = "ReviewedTitleMoreEntity",
  ReviewedTitleMoreTitle = "ReviewedTitleMoreTitle",
  ReviewedTitleViewing = "ReviewedTitleViewing",
  WatchlistTitlesJson = "WatchlistTitlesJson",
  WatchlistCollectionsJson = "WatchlistCollectionsJson",
  WatchlistEntityTitle = "WatchlistEntityTitle",
  WatchlistDirectorsJson = "WatchlistDirectorsJson",
  WatchlistPerformersJson = "WatchlistPerformersJson",
  WatchlistWritersJson = "WatchlistWritersJson",
}
