export enum SchemaNames {
  AllTimeStatsGradeDistribution = "AllTimeStatsGradeDistribution",
  AllTimeStatsJson = "AllTimeStatsJson",
  CastAndCrewJson = "CastAndCrewJson",
  CastAndCrewMemberTitle = "CastAndCrewMemberTitle",
  CollectionsJson = "CollectionsJson",
  CollectionTitle = "CollectionTitle",
  MarkdownRemark = "MarkdownRemark",
  MostWatchedPerson = "MostWatchedPerson",
  MostWatchedPersonViewing = "MostWatchedPersonViewing",
  MostWatchedTitle = "MostWatchedTitle",
  OverratedDisappointmentsJson = "OverratedDisappointmentsJson",
  ReviewedTitleMore = "ReviewedTitleMore",
  ReviewedTitleMoreCastAndCrewMember = "ReviewedTitleMoreCastAndCrewMember",
  ReviewedTitleMoreCollection = "ReviewedTitleMoreCollection",
  ReviewedTitleMoreTitle = "ReviewedTitleMoreTitle",
  ReviewedTitlesJson = "ReviewedTitlesJson",
  ReviewedTitleViewing = "ReviewedTitleViewing",
  StatsDistribution = "StatsDistribution",
  Title = "Title",
  UnderseenGemsJson = "UnderseenGemsJson",
  ViewingsJson = "ViewingsJson",
  WatchlistProgressDetail = "WatchlistProgressDetail",
  WatchlistProgressJson = "WatchlistProgressJson",
  WatchlistTitlesJson = "WatchlistTitlesJson",
  YearStatsJson = "YearStatsJson",
}
