export enum SchemaNames {
  AllTimeStatsGradeDistribution = "AllTimeStatsGradeDistribution",
  AllTimeStatsJson = "AllTimeStatsJson",
  MarkdownRemark = "MarkdownRemark",
  MostWatchedPerson = "MostWatchedPerson",
  MostWatchedPersonViewing = "MostWatchedPersonViewing",
  MostWatchedTitle = "MostWatchedTitle",
  OverratedDisappointmentsJson = "OverratedDisappointmentsJson",
  ReviewedTitleMore = "ReviewedTitleMore",
  ReviewedTitleMoreEntity = "ReviewedTitleMoreEntity",
  ReviewedTitleMoreTitle = "ReviewedTitleMoreTitle",
  ReviewedTitlesJson = "ReviewedTitlesJson",
  ReviewedTitleViewing = "ReviewedTitleViewing",
  StatsDistribution = "StatsDistribution",
  UnderseenGemsJson = "UnderseenGemsJson",
  ViewingsJson = "ViewingsJson",
  WatchlistCollectionsJson = "WatchlistCollectionsJson",
  WatchlistDirectorsJson = "WatchlistDirectorsJson",
  WatchlistEntityTitle = "WatchlistEntityTitle",
  WatchlistPerformersJson = "WatchlistPerformersJson",
  WatchlistTitlesJson = "WatchlistTitlesJson",
  WatchlistWritersJson = "WatchlistWritersJson",
  YearStatsJson = "YearStatsJson",
  WatchlistEntity = "WatchlistEntity",
  WatchlistProgressJson = "WatchlistProgressJson",
  WatchlistProgressDetail = "WatchlistProgressDetail",
}
