export default {
  overall: {
    movieCount: 155,
    newMovieCount: 97,
    viewingCount: 157,
  },
  decade: {
    stats: [
      {
        decade: "1920s",
        viewingCount: 11,
      },
      {
        decade: "1930s",
        viewingCount: 26,
      },
      {
        decade: "1940s",
        viewingCount: 6,
      },
      {
        decade: "1950s",
        viewingCount: 11,
      },
      {
        decade: "1960s",
        viewingCount: 6,
      },
      {
        decade: "1970s",
        viewingCount: 11,
      },
      {
        decade: "1980s",
        viewingCount: 19,
      },
      {
        decade: "1990s",
        viewingCount: 8,
      },
      {
        decade: "2000s",
        viewingCount: 9,
      },
      {
        decade: "2010s",
        viewingCount: 45,
      },
      {
        decade: "2020s",
        viewingCount: 5,
      },
    ],
  },
  venue: {
    stats: [
      {
        name: "4k UHD Blu-ray",
        viewingCount: 20,
      },
      {
        name: "Alamo Drafthouse Cinema - One Loudoun",
        viewingCount: 9,
      },
      {
        name: "Amazon",
        viewingCount: 9,
      },
      {
        name: "archive.org",
        viewingCount: 2,
      },
      {
        name: "Blu-ray",
        viewingCount: 39,
      },
      {
        name: "Criterion Channel",
        viewingCount: 5,
      },
      {
        name: "Disney+",
        viewingCount: 7,
      },
      {
        name: "DVD",
        viewingCount: 7,
      },
      {
        name: "FandangoNOW",
        viewingCount: 1,
      },
      {
        name: "HBO Max",
        viewingCount: 3,
      },
      {
        name: "Hulu",
        viewingCount: 2,
      },
      {
        name: "iTunes",
        viewingCount: 20,
      },
      {
        name: "Kanopy",
        viewingCount: 2,
      },
      {
        name: "Netflix",
        viewingCount: 4,
      },
      {
        name: "OK.ru",
        viewingCount: 10,
      },
      {
        name: "Shudder",
        viewingCount: 2,
      },
      {
        name: "TCM",
        viewingCount: 1,
      },
      {
        name: "VHS-rip",
        viewingCount: 5,
      },
      {
        name: "Vudu",
        viewingCount: 2,
      },
      {
        name: "Watch TCM",
        viewingCount: 2,
      },
      {
        name: "YouTube",
        viewingCount: 5,
      },
    ],
  },
  movies: {
    mostWatched: [
      {
        imdbId: "tt1259521",
        title: "The Cabin in the Woods",
        year: 2011,
        slug: "the-cabin-in-the-woods-2011",
        viewings: [
          {
            sequence: 815,
            slug: null,
            prettyDate: "Sat Feb 8, 2020",
            venue: "4k UHD Blu-ray",
          },
          {
            sequence: 956,
            slug: "the-cabin-in-the-woods-2011",
            prettyDate: "Tue Dec 22, 2020",
            venue: "4k UHD Blu-ray",
          },
        ],
        viewingCount: 2,
      },
      {
        imdbId: "tt4154756",
        title: "Avengers: Infinity War",
        year: 2018,
        slug: "avengers-infinity-war-2018",
        viewings: [
          {
            sequence: 824,
            slug: null,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
          },
          {
            sequence: 893,
            slug: "avengers-infinity-war-2018",
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
          },
        ],
        viewingCount: 2,
      },
    ],
  },
  directors: {
    mostWatched: [
      {
        fullName: "Anthony Russo",
        slug: null,
        viewingCount: 5,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Joe Russo",
        slug: null,
        viewingCount: 5,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "John Ford",
        slug: "john-ford",
        viewingCount: 5,
        viewings: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            venue: "iTunes",
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 867,
            prettyDate: "Fri Sep 11, 2020",
            venue: "iTunes",
            title: "Born Reckless",
            year: 1930,
            slug: "born-reckless-1930",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            venue: "iTunes",
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            venue: "VHS-rip",
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
          {
            sequence: 912,
            prettyDate: "Fri Nov 6, 2020",
            venue: "iTunes",
            title: "Up the River",
            year: 1930,
            slug: "up-the-river-1930",
          },
        ],
      },
      {
        fullName: "Lucio Fulci",
        slug: "lucio-fulci",
        viewingCount: 5,
        viewings: [
          {
            sequence: 873,
            prettyDate: "Mon Sep 21, 2020",
            venue: "DVD",
            title: "Massacre Time",
            year: 1966,
            slug: "the-brute-and-the-beast-1966",
          },
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            venue: "Blu-ray",
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            venue: "Blu-ray",
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            venue: "Blu-ray",
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            venue: "iTunes",
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
        ],
      },
      {
        fullName: "Val Guest",
        slug: null,
        viewingCount: 4,
        viewings: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            venue: "Blu-ray",
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            venue: "Blu-ray",
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            venue: "Blu-ray",
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
          {
            sequence: 915,
            prettyDate: "Tue Nov 10, 2020",
            venue: "Blu-ray",
            title: "The Camp on Blood Island",
            year: 1958,
            slug: "the-camp-on-blood-island-1958",
          },
        ],
      },
      {
        fullName: "Alfred Hitchcock",
        slug: "alfred-hitchcock",
        viewingCount: 3,
        viewings: [
          {
            sequence: 838,
            prettyDate: "Fri Jul 10, 2020",
            venue: "Kanopy",
            title: "Blackmail",
            year: 1929,
            slug: "blackmail-1929",
          },
          {
            sequence: 876,
            prettyDate: "Mon Sep 28, 2020",
            venue: "iTunes",
            title: "Murder!",
            year: 1930,
            slug: "murder-1930",
          },
          {
            sequence: 909,
            prettyDate: "Mon Nov 2, 2020",
            venue: "DVD",
            title: "Juno and the Paycock",
            year: 1930,
            slug: "juno-and-the-paycock-1930",
          },
        ],
      },
      {
        fullName: "Frank Tuttle",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            venue: "YouTube",
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            venue: "YouTube",
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            venue: "OK.ru",
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
        ],
      },
      {
        fullName: "Ingmar Bergman",
        slug: "ingmar-bergman",
        viewingCount: 3,
        viewings: [
          {
            sequence: 942,
            prettyDate: "Sun Dec 13, 2020",
            venue: "Criterion Channel",
            title: "Crisis",
            year: 1946,
            slug: "crisis-1946",
          },
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            venue: "DVD",
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 952,
            prettyDate: "Sun Dec 20, 2020",
            venue: "Criterion Channel",
            title: "A Ship to India",
            year: 1947,
            slug: "a-ship-to-india-1947",
          },
        ],
      },
      {
        fullName: "Sam Mendes",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 810,
            prettyDate: "Wed Jan 1, 2020",
            venue: "iTunes",
            title: "Skyfall",
            year: 2012,
            slug: null,
          },
          {
            sequence: 811,
            prettyDate: "Wed Jan 1, 2020",
            venue: "iTunes",
            title: "Spectre",
            year: 2015,
            slug: null,
          },
        ],
      },
      {
        fullName: "Roger Spottiswoode",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 814,
            prettyDate: "Tue Jan 28, 2020",
            venue: "Alamo Drafthouse Cinema - One Loudoun",
            title: "Terror Train",
            year: 1980,
            slug: null,
          },
          {
            sequence: 851,
            prettyDate: "Thu Aug 6, 2020",
            venue: "Netflix",
            title: "Tomorrow Never Dies",
            year: 1997,
            slug: "tomorrow-never-dies-1997",
          },
        ],
      },
      {
        fullName: "Drew Goddard",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 815,
            prettyDate: "Sat Feb 8, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Cabin in the Woods",
            year: 2011,
            slug: null,
          },
          {
            sequence: 956,
            prettyDate: "Tue Dec 22, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Cabin in the Woods",
            year: 2011,
            slug: "the-cabin-in-the-woods-2011",
          },
        ],
      },
      {
        fullName: "Jon Favreau",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 825,
            prettyDate: "Sat Apr 4, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man",
            year: 2008,
            slug: null,
          },
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
        ],
      },
      {
        fullName: "Joss Whedon",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
        ],
      },
      {
        fullName: "Hayao Miyazaki",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 833,
            prettyDate: "Thu Jun 11, 2020",
            venue: "Blu-ray",
            title: "My Neighbor Totoro",
            year: 1988,
            slug: null,
          },
          {
            sequence: 835,
            prettyDate: "Thu Jun 18, 2020",
            venue: "Blu-ray",
            title: "Kiki's Delivery Service",
            year: 1989,
            slug: null,
          },
        ],
      },
      {
        fullName: "James Gunn",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 836,
            prettyDate: "Sun Jul 5, 2020",
            venue: "4k UHD Blu-ray",
            title: "Guardians of the Galaxy",
            year: 2014,
            slug: null,
          },
          {
            sequence: 862,
            prettyDate: "Sat Aug 29, 2020",
            venue: "Disney+",
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            slug: "guardians-of-the-galaxy-vol-2-2017",
          },
        ],
      },
      {
        fullName: "Irving Cummings",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 837,
            prettyDate: "Thu Jul 9, 2020",
            venue: "YouTube",
            title: "Behind That Curtain",
            year: 1929,
            slug: "behind-that-curtain-1929",
          },
          {
            sequence: 928,
            prettyDate: "Fri Nov 27, 2020",
            venue: "YouTube",
            title: "A Holy Terror",
            year: 1931,
            slug: "a-holy-terror-1931",
          },
        ],
      },
      {
        fullName: "Peyton Reed",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 842,
            prettyDate: "Sat Jul 18, 2020",
            venue: "Disney+",
            title: "Ant-Man",
            year: 2015,
            slug: "ant-man-2015",
          },
          {
            sequence: 900,
            prettyDate: "Sat Oct 24, 2020",
            venue: "Disney+",
            title: "Ant-Man and the Wasp",
            year: 2018,
            slug: "ant-man-and-the-wasp-2018",
          },
        ],
      },
      {
        fullName: "Robert Milton",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 845,
            prettyDate: "Thu Jul 30, 2020",
            venue: "OK.ru",
            title: "Charming Sinners",
            year: 1929,
            slug: "charming-sinners-1929",
          },
          {
            sequence: 858,
            prettyDate: "Sat Aug 22, 2020",
            venue: "archive.org",
            title: "Behind the Make-Up",
            year: 1930,
            slug: "behind-the-make-up-1930",
          },
        ],
      },
      {
        fullName: "Tod Browning",
        slug: "tod-browning",
        viewingCount: 2,
        viewings: [
          {
            sequence: 854,
            prettyDate: "Mon Aug 17, 2020",
            venue: "DVD",
            title: "The Thirteenth Chair",
            year: 1929,
            slug: "the-thirteenth-chair-1929",
          },
          {
            sequence: 880,
            prettyDate: "Sun Oct 4, 2020",
            venue: "Blu-ray",
            title: "Dracula",
            year: 1931,
            slug: "dracula-1931",
          },
        ],
      },
      {
        fullName: "Lionel Barrymore",
        slug: null,
        viewingCount: 2,
        viewings: [
          {
            sequence: 855,
            prettyDate: "Tue Aug 18, 2020",
            venue: "archive.org",
            title: "The Unholy Night",
            year: 1929,
            slug: "the-unholy-night-1929",
          },
          {
            sequence: 895,
            prettyDate: "Thu Oct 22, 2020",
            venue: "TCM",
            title: "The Sea Bat",
            year: 1930,
            slug: "the-sea-bat-1930",
          },
        ],
      },
    ],
  },
  performers: {
    mostWatched: [
      {
        fullName: "William Powell",
        slug: "william-powell",
        viewingCount: 11,
        viewings: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            venue: "YouTube",
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 845,
            prettyDate: "Thu Jul 30, 2020",
            venue: "OK.ru",
            title: "Charming Sinners",
            year: 1929,
            slug: "charming-sinners-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            venue: "YouTube",
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 849,
            prettyDate: "Sun Aug 2, 2020",
            venue: "OK.ru",
            title: "Pointed Heels",
            year: 1929,
            slug: "pointed-heels-1929",
          },
          {
            sequence: 858,
            prettyDate: "Sat Aug 22, 2020",
            venue: "archive.org",
            title: "Behind the Make-Up",
            year: 1930,
            slug: "behind-the-make-up-1930",
          },
          {
            sequence: 859,
            prettyDate: "Sat Aug 22, 2020",
            venue: "OK.ru",
            title: "Interference",
            year: 1928,
            slug: "interference-1928",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            venue: "OK.ru",
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
          {
            sequence: 870,
            prettyDate: "Sun Sep 13, 2020",
            venue: "OK.ru",
            title: "For the Defense",
            year: 1930,
            slug: "for-the-defense-1930",
          },
          {
            sequence: 877,
            prettyDate: "Wed Sep 30, 2020",
            venue: "OK.ru",
            title: "Street of Chance",
            year: 1930,
            slug: "street-of-chance-1930",
          },
          {
            sequence: 885,
            prettyDate: "Sat Oct 10, 2020",
            venue: "OK.ru",
            title: "Shadow of the Law",
            year: 1930,
            slug: "shadow-of-the-law-1930",
          },
          {
            sequence: 925,
            prettyDate: "Wed Nov 25, 2020",
            venue: "OK.ru",
            title: "Ladies' Man",
            year: 1931,
            slug: "ladies-man-1931",
          },
        ],
      },
      {
        fullName: "Chris Hemsworth",
        slug: null,
        viewingCount: 10,
        viewings: [
          {
            sequence: 815,
            prettyDate: "Sat Feb 8, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Cabin in the Woods",
            year: 2011,
            slug: null,
          },
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 828,
            prettyDate: "Sat May 9, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor",
            year: 2011,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 832,
            prettyDate: "Sat Jun 6, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: The Dark World",
            year: 2013,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 875,
            prettyDate: "Sat Sep 26, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: Ragnarok",
            year: 2017,
            slug: "thor-ragnarok-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 956,
            prettyDate: "Tue Dec 22, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Cabin in the Woods",
            year: 2011,
            slug: "the-cabin-in-the-woods-2011",
          },
        ],
      },
      {
        fullName: "Robert Downey Jr.",
        slug: null,
        viewingCount: 10,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 825,
            prettyDate: "Sat Apr 4, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man",
            year: 2008,
            slug: null,
          },
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 831,
            prettyDate: "Sun May 31, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 3",
            year: 2013,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Chris Evans",
        slug: null,
        viewingCount: 9,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 829,
            prettyDate: "Sat May 16, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The First Avenger",
            year: 2011,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Samuel L. Jackson",
        slug: null,
        viewingCount: 9,
        viewings: [
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 829,
            prettyDate: "Sat May 16, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The First Avenger",
            year: 2011,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 913,
            prettyDate: "Sun Nov 8, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain Marvel",
            year: 2019,
            slug: "captain-marvel-2019",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            venue: "4k UHD Blu-ray",
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
          {
            sequence: 966,
            prettyDate: "Thu Dec 31, 2020",
            venue: "HBO Max",
            title: "Glass",
            year: 2019,
            slug: "glass-2019",
          },
        ],
      },
      {
        fullName: "Gwyneth Paltrow",
        slug: null,
        viewingCount: 8,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 825,
            prettyDate: "Sat Apr 4, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man",
            year: 2008,
            slug: null,
          },
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 831,
            prettyDate: "Sun May 31, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 3",
            year: 2013,
            slug: null,
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Paul Bettany",
        slug: null,
        viewingCount: 8,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 825,
            prettyDate: "Sat Apr 4, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man",
            year: 2008,
            slug: null,
          },
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 831,
            prettyDate: "Sun May 31, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 3",
            year: 2013,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
        ],
      },
      {
        fullName: "Scarlett Johansson",
        slug: null,
        viewingCount: 8,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Don Cheadle",
        slug: null,
        viewingCount: 7,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 831,
            prettyDate: "Sun May 31, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 3",
            year: 2013,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Tom Hiddleston",
        slug: null,
        viewingCount: 7,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 828,
            prettyDate: "Sat May 9, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor",
            year: 2011,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 832,
            prettyDate: "Sat Jun 6, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: The Dark World",
            year: 2013,
            slug: null,
          },
          {
            sequence: 875,
            prettyDate: "Sat Sep 26, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: Ragnarok",
            year: 2017,
            slug: "thor-ragnarok-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Anthony Mackie",
        slug: null,
        viewingCount: 7,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 842,
            prettyDate: "Sat Jul 18, 2020",
            venue: "Disney+",
            title: "Ant-Man",
            year: 2015,
            slug: "ant-man-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Dave Bautista",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 811,
            prettyDate: "Wed Jan 1, 2020",
            venue: "iTunes",
            title: "Spectre",
            year: 2015,
            slug: null,
          },
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 836,
            prettyDate: "Sun Jul 5, 2020",
            venue: "4k UHD Blu-ray",
            title: "Guardians of the Galaxy",
            year: 2014,
            slug: null,
          },
          {
            sequence: 862,
            prettyDate: "Sat Aug 29, 2020",
            venue: "Disney+",
            title: "Guardians of the Galaxy Vol. 2",
            year: 2017,
            slug: "guardians-of-the-galaxy-vol-2-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Kerry Condon",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Idris Elba",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 828,
            prettyDate: "Sat May 9, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor",
            year: 2011,
            slug: null,
          },
          {
            sequence: 832,
            prettyDate: "Sat Jun 6, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: The Dark World",
            year: 2013,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 875,
            prettyDate: "Sat Sep 26, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: Ragnarok",
            year: 2017,
            slug: "thor-ragnarok-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
        ],
      },
      {
        fullName: "Mark Ruffalo",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 875,
            prettyDate: "Sat Sep 26, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: Ragnarok",
            year: 2017,
            slug: "thor-ragnarok-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Sebastian Stan",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 829,
            prettyDate: "Sat May 16, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The First Avenger",
            year: 2011,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Tom Holland",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            venue: "4k UHD Blu-ray",
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Jon Favreau",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 825,
            prettyDate: "Sat Apr 4, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man",
            year: 2008,
            slug: null,
          },
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 831,
            prettyDate: "Sun May 31, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 3",
            year: 2013,
            slug: null,
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            venue: "4k UHD Blu-ray",
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Brian Schaeffer",
        slug: null,
        viewingCount: 6,
        viewings: [
          {
            sequence: 827,
            prettyDate: "Sat May 2, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 2",
            year: 2010,
            slug: null,
          },
          {
            sequence: 831,
            prettyDate: "Sun May 31, 2020",
            venue: "4k UHD Blu-ray",
            title: "Iron Man 3",
            year: 2013,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Bela Lugosi",
        slug: "bela-lugosi",
        viewingCount: 6,
        viewings: [
          {
            sequence: 854,
            prettyDate: "Mon Aug 17, 2020",
            venue: "DVD",
            title: "The Thirteenth Chair",
            year: 1929,
            slug: "the-thirteenth-chair-1929",
          },
          {
            sequence: 880,
            prettyDate: "Sun Oct 4, 2020",
            venue: "Blu-ray",
            title: "Dracula",
            year: 1931,
            slug: "dracula-1931",
          },
          {
            sequence: 886,
            prettyDate: "Sat Oct 10, 2020",
            venue: "VHS-rip",
            title: "Renegades",
            year: 1930,
            slug: "renegades-1930",
          },
          {
            sequence: 922,
            prettyDate: "Tue Nov 24, 2020",
            venue: "VHS-rip",
            title: "Wild Company",
            year: 1930,
            slug: "wild-company-1930",
          },
          {
            sequence: 923,
            prettyDate: "Tue Nov 24, 2020",
            venue: "VHS-rip",
            title: "Oh, for a Man!",
            year: 1930,
            slug: "oh-for-a-man-1930",
          },
          {
            sequence: 926,
            prettyDate: "Thu Nov 26, 2020",
            venue: "YouTube",
            title: "The Black Camel",
            year: 1931,
            slug: "the-black-camel-1931",
          },
        ],
      },
    ],
  },
  writers: {
    mostWatched: [
      {
        fullName: "Christopher Markus",
        slug: null,
        viewingCount: 7,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 829,
            prettyDate: "Sat May 16, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The First Avenger",
            year: 2011,
            slug: null,
          },
          {
            sequence: 832,
            prettyDate: "Sat Jun 6, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: The Dark World",
            year: 2013,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Stephen McFeely",
        slug: null,
        viewingCount: 7,
        viewings: [
          {
            sequence: 824,
            prettyDate: "Sat Mar 28, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: null,
          },
          {
            sequence: 829,
            prettyDate: "Sat May 16, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The First Avenger",
            year: 2011,
            slug: null,
          },
          {
            sequence: 832,
            prettyDate: "Sat Jun 6, 2020",
            venue: "4k UHD Blu-ray",
            title: "Thor: The Dark World",
            year: 2013,
            slug: null,
          },
          {
            sequence: 834,
            prettyDate: "Sat Jun 13, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: The Winter Soldier",
            year: 2014,
            slug: null,
          },
          {
            sequence: 844,
            prettyDate: "Sat Jul 25, 2020",
            venue: "4k UHD Blu-ray",
            title: "Captain America: Civil War",
            year: 2016,
            slug: "captain-america-civil-war-2016",
          },
          {
            sequence: 893,
            prettyDate: "Sat Oct 17, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Infinity War",
            year: 2018,
            slug: "avengers-infinity-war-2018",
          },
          {
            sequence: 918,
            prettyDate: "Sat Nov 14, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Endgame",
            year: 2019,
            slug: "avengers-endgame-2019",
          },
        ],
      },
      {
        fullName: "Lucio Fulci",
        slug: null,
        viewingCount: 5,
        viewings: [
          {
            sequence: 873,
            prettyDate: "Mon Sep 21, 2020",
            venue: "DVD",
            title: "Massacre Time",
            year: 1966,
            slug: "the-brute-and-the-beast-1966",
          },
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            venue: "Blu-ray",
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            venue: "Blu-ray",
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            venue: "Blu-ray",
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            venue: "iTunes",
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
        ],
      },
      {
        fullName: "Joss Whedon",
        slug: null,
        viewingCount: 4,
        viewings: [
          {
            sequence: 815,
            prettyDate: "Sat Feb 8, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Cabin in the Woods",
            year: 2011,
            slug: null,
          },
          {
            sequence: 830,
            prettyDate: "Sat May 23, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Avengers",
            year: 2012,
            slug: null,
          },
          {
            sequence: 839,
            prettyDate: "Sat Jul 11, 2020",
            venue: "4k UHD Blu-ray",
            title: "Avengers: Age of Ultron",
            year: 2015,
            slug: "avengers-age-of-ultron-2015",
          },
          {
            sequence: 956,
            prettyDate: "Tue Dec 22, 2020",
            venue: "4k UHD Blu-ray",
            title: "The Cabin in the Woods",
            year: 2011,
            slug: "the-cabin-in-the-woods-2011",
          },
        ],
      },
      {
        fullName: "Val Guest",
        slug: null,
        viewingCount: 4,
        viewings: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            venue: "Blu-ray",
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            venue: "Blu-ray",
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            venue: "Blu-ray",
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
          {
            sequence: 915,
            prettyDate: "Tue Nov 10, 2020",
            venue: "Blu-ray",
            title: "The Camp on Blood Island",
            year: 1958,
            slug: "the-camp-on-blood-island-1958",
          },
        ],
      },
      {
        fullName: "Roberto Gianviti",
        slug: null,
        viewingCount: 4,
        viewings: [
          {
            sequence: 874,
            prettyDate: "Thu Sep 24, 2020",
            venue: "Blu-ray",
            title: "One on Top of the Other",
            year: 1969,
            slug: "one-on-top-of-the-other-1969",
          },
          {
            sequence: 896,
            prettyDate: "Thu Oct 22, 2020",
            venue: "Blu-ray",
            title: "The Conspiracy of Torture",
            year: 1969,
            slug: "the-conspiracy-of-torture-1969",
          },
          {
            sequence: 897,
            prettyDate: "Fri Oct 23, 2020",
            venue: "Blu-ray",
            title: "A Lizard in a Woman's Skin",
            year: 1971,
            slug: "a-lizard-in-a-womans-skin-1971",
          },
          {
            sequence: 901,
            prettyDate: "Tue Oct 27, 2020",
            venue: "iTunes",
            title: "Don't Torture a Duckling",
            year: 1972,
            slug: "dont-torture-a-duckling-1972",
          },
        ],
      },
      {
        fullName: "Neal Purvis",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 810,
            prettyDate: "Wed Jan 1, 2020",
            venue: "iTunes",
            title: "Skyfall",
            year: 2012,
            slug: null,
          },
          {
            sequence: 811,
            prettyDate: "Wed Jan 1, 2020",
            venue: "iTunes",
            title: "Spectre",
            year: 2015,
            slug: null,
          },
          {
            sequence: 852,
            prettyDate: "Thu Aug 6, 2020",
            venue: "Netflix",
            title: "The World Is Not Enough",
            year: 1999,
            slug: "the-world-is-not-enough-1999",
          },
        ],
      },
      {
        fullName: "Robert Wade",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 810,
            prettyDate: "Wed Jan 1, 2020",
            venue: "iTunes",
            title: "Skyfall",
            year: 2012,
            slug: null,
          },
          {
            sequence: 811,
            prettyDate: "Wed Jan 1, 2020",
            venue: "iTunes",
            title: "Spectre",
            year: 2015,
            slug: null,
          },
          {
            sequence: 852,
            prettyDate: "Thu Aug 6, 2020",
            venue: "Netflix",
            title: "The World Is Not Enough",
            year: 1999,
            slug: "the-world-is-not-enough-1999",
          },
        ],
      },
      {
        fullName: "Alfred Hitchcock",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 838,
            prettyDate: "Fri Jul 10, 2020",
            venue: "Kanopy",
            title: "Blackmail",
            year: 1929,
            slug: "blackmail-1929",
          },
          {
            sequence: 876,
            prettyDate: "Mon Sep 28, 2020",
            venue: "iTunes",
            title: "Murder!",
            year: 1930,
            slug: "murder-1930",
          },
          {
            sequence: 909,
            prettyDate: "Mon Nov 2, 2020",
            venue: "DVD",
            title: "Juno and the Paycock",
            year: 1930,
            slug: "juno-and-the-paycock-1930",
          },
        ],
      },
      {
        fullName: "James Kevin McGuinness",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            venue: "iTunes",
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            venue: "iTunes",
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            venue: "VHS-rip",
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
        ],
      },
      {
        fullName: "John Stone",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 840,
            prettyDate: "Sun Jul 12, 2020",
            venue: "iTunes",
            title: "The Black Watch",
            year: 1929,
            slug: "the-black-watch-1929",
          },
          {
            sequence: 883,
            prettyDate: "Fri Oct 9, 2020",
            venue: "VHS-rip",
            title: "Salute",
            year: 1929,
            slug: "salute-1929",
          },
          {
            sequence: 922,
            prettyDate: "Tue Nov 24, 2020",
            venue: "VHS-rip",
            title: "Wild Company",
            year: 1930,
            slug: "wild-company-1930",
          },
        ],
      },
      {
        fullName: "S.S. Van Dine",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 841,
            prettyDate: "Fri Jul 17, 2020",
            venue: "YouTube",
            title: "The Canary Murder Case",
            year: 1929,
            slug: "the-canary-murder-case-1929",
          },
          {
            sequence: 846,
            prettyDate: "Thu Jul 30, 2020",
            venue: "YouTube",
            title: "The Greene Murder Case",
            year: 1929,
            slug: "the-greene-murder-case-1929",
          },
          {
            sequence: 860,
            prettyDate: "Wed Aug 26, 2020",
            venue: "OK.ru",
            title: "The Benson Murder Case",
            year: 1930,
            slug: "the-benson-murder-case-1930",
          },
        ],
      },
      {
        fullName: "Bruce Feirstein",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 850,
            prettyDate: "Tue Aug 4, 2020",
            venue: "Netflix",
            title: "GoldenEye",
            year: 1995,
            slug: "goldeneye-1995",
          },
          {
            sequence: 851,
            prettyDate: "Thu Aug 6, 2020",
            venue: "Netflix",
            title: "Tomorrow Never Dies",
            year: 1997,
            slug: "tomorrow-never-dies-1997",
          },
          {
            sequence: 852,
            prettyDate: "Thu Aug 6, 2020",
            venue: "Netflix",
            title: "The World Is Not Enough",
            year: 1999,
            slug: "the-world-is-not-enough-1999",
          },
        ],
      },
      {
        fullName: "Jimmy Sangster",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 853,
            prettyDate: "Sun Aug 16, 2020",
            venue: "Blu-ray",
            title: "X the Unknown",
            year: 1956,
            slug: "x-the-unknown-1956",
          },
          {
            sequence: 872,
            prettyDate: "Sat Sep 19, 2020",
            venue: "Blu-ray",
            title: "The Curse of Frankenstein",
            year: 1957,
            slug: "the-curse-of-frankenstein-1957",
          },
          {
            sequence: 936,
            prettyDate: "Tue Dec 8, 2020",
            venue: "Blu-ray",
            title: "Horror of Dracula",
            year: 1958,
            slug: "horror-of-dracula-1958",
          },
        ],
      },
      {
        fullName: "Nigel Kneale",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 856,
            prettyDate: "Wed Aug 19, 2020",
            venue: "Blu-ray",
            title: "The Quatermass Xperiment",
            year: 1955,
            slug: "the-quatermass-xperiment-1955",
          },
          {
            sequence: 861,
            prettyDate: "Thu Aug 27, 2020",
            venue: "Blu-ray",
            title: "The Abominable Snowman",
            year: 1957,
            slug: "the-abominable-snowman-1957",
          },
          {
            sequence: 911,
            prettyDate: "Thu Nov 5, 2020",
            venue: "Blu-ray",
            title: "Quatermass 2",
            year: 1957,
            slug: "quatermass-2-1957",
          },
        ],
      },
      {
        fullName: "Chris McKenna",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 900,
            prettyDate: "Sat Oct 24, 2020",
            venue: "Disney+",
            title: "Ant-Man and the Wasp",
            year: 2018,
            slug: "ant-man-and-the-wasp-2018",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            venue: "4k UHD Blu-ray",
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Erik Sommers",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 865,
            prettyDate: "Sat Sep 5, 2020",
            venue: "iTunes",
            title: "Spider-Man: Homecoming",
            year: 2017,
            slug: "spider-man-homecoming-2017",
          },
          {
            sequence: 900,
            prettyDate: "Sat Oct 24, 2020",
            venue: "Disney+",
            title: "Ant-Man and the Wasp",
            year: 2018,
            slug: "ant-man-and-the-wasp-2018",
          },
          {
            sequence: 921,
            prettyDate: "Sat Nov 21, 2020",
            venue: "4k UHD Blu-ray",
            title: "Spider-Man: Far from Home",
            year: 2019,
            slug: "spider-man-far-from-home-2019",
          },
        ],
      },
      {
        fullName: "Dudley Nichols",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 867,
            prettyDate: "Fri Sep 11, 2020",
            venue: "iTunes",
            title: "Born Reckless",
            year: 1930,
            slug: "born-reckless-1930",
          },
          {
            sequence: 868,
            prettyDate: "Fri Sep 11, 2020",
            venue: "iTunes",
            title: "Men Without Women",
            year: 1930,
            slug: "men-without-women-1930",
          },
          {
            sequence: 926,
            prettyDate: "Thu Nov 26, 2020",
            venue: "YouTube",
            title: "The Black Camel",
            year: 1931,
            slug: "the-black-camel-1931",
          },
        ],
      },
      {
        fullName: "Adam Green",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 871,
            prettyDate: "Sat Sep 19, 2020",
            venue: "iTunes",
            title: "Hatchet",
            year: 2006,
            slug: "hatchet-2006",
          },
          {
            sequence: 890,
            prettyDate: "Thu Oct 15, 2020",
            venue: "Blu-ray",
            title: "Hatchet II",
            year: 2010,
            slug: "hatchet-ii-2010",
          },
          {
            sequence: 920,
            prettyDate: "Thu Nov 19, 2020",
            venue: "Blu-ray",
            title: "Hatchet III",
            year: 2013,
            slug: "hatchet-iii-2013",
          },
        ],
      },
      {
        fullName: "Ingmar Bergman",
        slug: null,
        viewingCount: 3,
        viewings: [
          {
            sequence: 942,
            prettyDate: "Sun Dec 13, 2020",
            venue: "Criterion Channel",
            title: "Crisis",
            year: 1946,
            slug: "crisis-1946",
          },
          {
            sequence: 945,
            prettyDate: "Wed Dec 16, 2020",
            venue: "DVD",
            title: "It Rains on Our Love",
            year: 1946,
            slug: "it-rains-on-our-love-1946",
          },
          {
            sequence: 952,
            prettyDate: "Sun Dec 20, 2020",
            venue: "Criterion Channel",
            title: "A Ship to India",
            year: 1947,
            slug: "a-ship-to-india-1947",
          },
        ],
      },
    ],
  },
  year: {
    nodes: [
      {
        year: "all",
      },
      {
        year: "2021",
      },
      {
        year: "2020",
      },
      {
        year: "2019",
      },
      {
        year: "2018",
      },
      {
        year: "2017",
      },
      {
        year: "2016",
      },
      {
        year: "2015",
      },
      {
        year: "2014",
      },
      {
        year: "2013",
      },
      {
        year: "2012",
      },
    ],
  },
};
