export default {
  viewing: {
    nodes: [
      {
        sequence: 1113,
        viewingDate: "Saturday Jun 12, 2021",
        releaseDate: "1989-02-09",
        title: "Weekend at Bernie's",
        venue: "Hulu",
        year: 1989,
        sortTitle: "Weekend at Bernie's (1989)",
        slug: "weekend-at-bernies-1989",
      },
      {
        sequence: 1112,
        viewingDate: "Thursday Jun 10, 2021",
        releaseDate: "1976-07-23",
        title: "The Human Tornado",
        venue: "Blu-ray",
        year: 1976,
        sortTitle: "Human Tornado (1976)",
        slug: "the-human-tornado-1976",
      },
      {
        sequence: 1111,
        viewingDate: "Thursday Jun 10, 2021",
        releaseDate: "2010-03-12",
        title: "Gone with the Pope",
        venue: "Arrow Player",
        year: 2010,
        sortTitle: "Gone with the Pope (2010)",
        slug: "gone-with-the-pope-2010",
      },
      {
        sequence: 1,
        viewingDate: "Thursday Jan 5, 2012",
        releaseDate: "2011-12-12",
        title: "The Girl with the Dragon Tattoo",
        venue: "AMC Tysons Corner 16",
        year: 2011,
        sortTitle: "Girl with the Dragon Tattoo (2011)",
        slug: null,
      },
    ],
  },
};
