export default {
  watchlist: {
    nodes: [
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0019035",
        performerNames: ["William Powell"],
        releaseDate: "1928-11-05",
        reviewsSlug: "interference-1928",
        sortTitle: "Interference (1928)",
        title: "Interference",
        year: 1928,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0019745",
        performerNames: ["William Powell"],
        releaseDate: "1929-01-15",
        reviewsSlug: "the-canary-murder-case-1929",
        sortTitle: "Canary Murder Case (1929)",
        title: "The Canary Murder Case",
        year: 1929,
        writerNames: [],
      },
      {
        directorNames: ["John Ford"],
        collectionNames: [],
        imdbId: "tt0019699",
        performerNames: [],
        releaseDate: "1929-05-08",
        reviewsSlug: "the-black-watch-1929",
        sortTitle: "Black Watch (1929)",
        title: "The Black Watch",
        year: 1929,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0019684",
        performerNames: ["Boris Karloff"],
        releaseDate: "1929-06-28",
        reviewsSlug: "behind-that-curtain-1929",
        sortTitle: "Behind That Curtain (1929)",
        title: "Behind That Curtain",
        year: 1929,
        writerNames: [],
      },
      {
        directorNames: ["Alfred Hitchcock"],
        collectionNames: [],
        imdbId: "tt0019702",
        performerNames: [],
        releaseDate: "1929-07-28",
        reviewsSlug: "blackmail-1929",
        sortTitle: "Blackmail (1929)",
        title: "Blackmail",
        year: 1929,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023694",
        performerNames: ["Bela Lugosi"],
        releaseDate: "1932-07-28",
        reviewsSlug: null,
        sortTitle: "White Zombie (1932)",
        title: "White Zombie",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023038",
        performerNames: ["John Wayne"],
        releaseDate: "1932-08-01",
        reviewsSlug: null,
        sortTitle: "Hurricane Express (1932)",
        title: "The Hurricane Express",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0022753",
        performerNames: ["Bela Lugosi"],
        releaseDate: "1932-08-04",
        reviewsSlug: null,
        sortTitle: "Chandu the Magician (1932)",
        title: "Chandu the Magician",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0022814",
        performerNames: ["Cary Grant"],
        releaseDate: "1932-08-12",
        reviewsSlug: null,
        sortTitle: "Devil and the Deep (1932)",
        title: "Devil and the Deep",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023396",
        performerNames: ["John Wayne"],
        releaseDate: "1932-08-27",
        reviewsSlug: null,
        sortTitle: "Ride Him, Cowboy (1932)",
        title: "Ride Him, Cowboy",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0022676",
        performerNames: ["Humphrey Bogart"],
        releaseDate: "1932-09-10",
        reviewsSlug: "big-city-blues-1932",
        sortTitle: "Big City Blues (1932)",
        title: "Big City Blues",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0022698",
        performerNames: ["Cary Grant"],
        releaseDate: "1932-09-14",
        reviewsSlug: null,
        sortTitle: "Blonde Venus (1932)",
        title: "Blonde Venus",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: ["Howard Hawks"],
        collectionNames: [],
        imdbId: "tt0023594",
        performerNames: [],
        releaseDate: "1932-09-22",
        reviewsSlug: null,
        sortTitle: "Tiger Shark (1932)",
        title: "Tiger Shark",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0022735",
        performerNames: ["Bette Davis"],
        releaseDate: "1932-09-26",
        reviewsSlug: null,
        sortTitle: "Cabin in the Cotton (1932)",
        title: "The Cabin in the Cotton",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0022681",
        performerNames: ["John Wayne"],
        releaseDate: "1932-09-29",
        reviewsSlug: null,
        sortTitle: "Big Stampede (1932)",
        title: "The Big Stampede",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023305",
        performerNames: ["William Powell"],
        releaseDate: "1932-10-04",
        reviewsSlug: null,
        sortTitle: "One Way Passage (1932)",
        title: "One Way Passage",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023576",
        performerNames: ["John Wayne"],
        releaseDate: "1932-10-06",
        reviewsSlug: null,
        sortTitle: "That's My Boy (1932)",
        title: "That's My Boy",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023293",
        performerNames: ["Boris Karloff"],
        releaseDate: "1932-10-19",
        reviewsSlug: null,
        sortTitle: "Old Dark House (1932)",
        title: "The Old Dark House",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023028",
        performerNames: ["Cary Grant"],
        releaseDate: "1932-10-28",
        reviewsSlug: null,
        sortTitle: "Hot Saturday (1932)",
        title: "Hot Saturday",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023590",
        performerNames: ["Bette Davis", "Humphrey Bogart"],
        releaseDate: "1932-10-28",
        reviewsSlug: null,
        sortTitle: "Three on a Match (1932)",
        title: "Three on a Match",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: ["John Ford"],
        collectionNames: [],
        imdbId: "tt0022615",
        performerNames: [],
        releaseDate: "1932-11-03",
        reviewsSlug: null,
        sortTitle: "Air Mail (1932)",
        title: "Air Mail",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023194",
        performerNames: ["Boris Karloff"],
        releaseDate: "1932-11-05",
        reviewsSlug: null,
        sortTitle: "Mask of Fu Manchu (1932)",
        title: "The Mask of Fu Manchu",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0024188",
        performerNames: ["Bela Lugosi"],
        releaseDate: "1932-12-01",
        reviewsSlug: null,
        sortTitle: "Island of Lost Souls (1932)",
        title: "Island of Lost Souls",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023935",
        performerNames: ["Bela Lugosi"],
        releaseDate: "1932-12-05",
        reviewsSlug: null,
        sortTitle: "Death Kiss (1932)",
        title: "The Death Kiss",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: ["John Ford"],
        collectionNames: [],
        imdbId: "tt0022897",
        performerNames: [],
        releaseDate: "1932-12-08",
        reviewsSlug: null,
        sortTitle: "Flesh (1932)",
        title: "Flesh",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023125",
        performerNames: ["William Powell"],
        releaseDate: "1932-12-10",
        reviewsSlug: null,
        sortTitle: "Lawyer Man (1932)",
        title: "Lawyer Man",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0022981",
        performerNames: ["John Wayne"],
        releaseDate: "1932-12-17",
        reviewsSlug: null,
        sortTitle: "Haunted Gold (1932)",
        title: "Haunted Gold",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: ["Universal Monsters"],
        imdbId: "tt0023245",
        performerNames: ["Boris Karloff"],
        releaseDate: "1932-12-22",
        reviewsSlug: null,
        sortTitle: "Mummy (1932)",
        title: "The Mummy",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023169",
        performerNames: ["Cary Grant"],
        releaseDate: "1932-12-23",
        reviewsSlug: null,
        sortTitle: "Madame Butterfly (1932)",
        title: "Madame Butterfly",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0023731",
        performerNames: ["Bette Davis"],
        releaseDate: "1932-12-24",
        reviewsSlug: null,
        sortTitle: "20,000 Years in Sing Sing (1932)",
        title: "20,000 Years in Sing Sing",
        year: 1932,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0024426",
        performerNames: ["Bette Davis"],
        releaseDate: "1933-01-25",
        reviewsSlug: null,
        sortTitle: "Parachute Jumper (1933)",
        title: "Parachute Jumper",
        year: 1933,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0024548",
        performerNames: ["Cary Grant"],
        releaseDate: "1933-01-27",
        reviewsSlug: null,
        sortTitle: "She Done Him Wrong (1933)",
        title: "She Done Him Wrong",
        year: 1933,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0024781",
        performerNames: ["Cary Grant"],
        releaseDate: "1933-02-17",
        reviewsSlug: null,
        sortTitle: "Woman Accused (1933)",
        title: "The Woman Accused",
        year: 1933,
        writerNames: [],
      },
      {
        directorNames: ["Howard Hawks"],
        collectionNames: [],
        imdbId: "tt0024675",
        performerNames: [],
        releaseDate: "1933-03-03",
        reviewsSlug: null,
        sortTitle: "Today We Live (1933)",
        title: "Today We Live",
        year: 1933,
        writerNames: [],
      },
      {
        directorNames: ["Howard Hawks"],
        collectionNames: [],
        imdbId: "tt0038355",
        performerNames: ["Humphrey Bogart"],
        releaseDate: "1946-08-22",
        reviewsSlug: null,
        sortTitle: "Big Sleep (1946)",
        title: "The Big Sleep",
        year: 1946,
        writerNames: ["Leigh Brackett", "Raymond Chandler"],
      },
      {
        directorNames: [],
        collectionNames: ["Hammer Films", "Frankenstein"],
        imdbId: "tt0050894",
        performerNames: ["Peter Cushing"],
        releaseDate: "1958-06-13",
        reviewsSlug: null,
        sortTitle: "Revenge of Frankenstein (1958)",
        title: "The Revenge of Frankenstein",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0051819",
        performerNames: ["Frank Sinatra"],
        releaseDate: "1958-06-18",
        reviewsSlug: null,
        sortTitle: "Kings Go Forth (1958)",
        title: "Kings Go Forth",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: ["Hammer Films"],
        imdbId: "tt0052207",
        performerNames: [],
        releaseDate: "1958-06-18",
        reviewsSlug: null,
        sortTitle: "Snorkel (1958)",
        title: "The Snorkel",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0051987",
        performerNames: ["Steve McQueen"],
        releaseDate: "1958-06-22",
        reviewsSlug: null,
        sortTitle: "Never Love a Stranger (1958)",
        title: "Never Love a Stranger",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0051773",
        performerNames: ["Cary Grant"],
        releaseDate: "1958-06-26",
        reviewsSlug: null,
        sortTitle: "Indiscreet (1958)",
        title: "Indiscreet",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: ["Roger Corman"],
        collectionNames: [],
        imdbId: "tt0052279",
        performerNames: [],
        releaseDate: "1958-07-01",
        reviewsSlug: null,
        sortTitle: "Teenage Cave Man (1958)",
        title: "Teenage Cave Man",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0051402",
        performerNames: ["Christopher Lee"],
        releaseDate: "1958-07-10",
        reviewsSlug: null,
        sortTitle: "Missiles from Hell (1958)",
        title: "Missiles from Hell",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0051622",
        performerNames: ["Vincent Price"],
        releaseDate: "1958-07-16",
        reviewsSlug: null,
        sortTitle: "Fly (1958)",
        title: "The Fly",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: ["Frankenstein"],
        imdbId: "tt0051630",
        performerNames: ["Boris Karloff"],
        releaseDate: "1958-07-20",
        reviewsSlug: null,
        sortTitle: "Frankenstein 1970 (1958)",
        title: "Frankenstein 1970",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: ["Roger Corman"],
        collectionNames: [],
        imdbId: "tt0052188",
        performerNames: [],
        releaseDate: "1958-08-01",
        reviewsSlug: null,
        sortTitle: "She Gods of Shark Reef (1958)",
        title: "She Gods of Shark Reef",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0051500",
        performerNames: ["Jack Nicholson"],
        releaseDate: "1958-08-17",
        reviewsSlug: "the-cry-baby-killer-1958",
        sortTitle: "Cry Baby Killer (1958)",
        title: "The Cry Baby Killer",
        year: 1958,
        writerNames: [],
      },
      {
        directorNames: ["Robert Altman"],
        collectionNames: [],
        imdbId: "tt0078481",
        performerNames: [],
        releaseDate: "1978-09-12",
        reviewsSlug: null,
        sortTitle: "Wedding (1978)",
        title: "A Wedding",
        year: 1978,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0077413",
        performerNames: ["Bette Davis"],
        releaseDate: "1978-09-29",
        reviewsSlug: null,
        sortTitle: "Death on the Nile (1978)",
        title: "Death on the Nile",
        year: 1978,
        writerNames: ["Anthony Shaffer"],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0077621",
        performerNames: ["Jack Nicholson"],
        releaseDate: "1978-10-06",
        reviewsSlug: null,
        sortTitle: "Goin' South (1978)",
        title: "Goin' South",
        year: 1978,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0104348",
        performerNames: ["Jack Lemmon"],
        releaseDate: "1992-08-30",
        reviewsSlug: null,
        sortTitle: "Glengarry Glen Ross (1992)",
        title: "Glengarry Glen Ross",
        year: 1992,
        writerNames: ["David Mamet"],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0103919",
        performerNames: [],
        releaseDate: "1992-09-11",
        reviewsSlug: null,
        sortTitle: "Candyman (1992)",
        title: "Candyman",
        year: 1992,
        writerNames: ["Clive Barker"],
      },
      {
        directorNames: ["Woody Allen"],
        collectionNames: [],
        imdbId: "tt0104466",
        performerNames: [],
        releaseDate: "1992-09-14",
        reviewsSlug: null,
        sortTitle: "Husbands and Wives (1992)",
        title: "Husbands and Wives",
        year: 1992,
        writerNames: [],
      },
      {
        directorNames: ["Ridley Scott"],
        collectionNames: [],
        imdbId: "tt0103594",
        performerNames: [],
        releaseDate: "1992-10-08",
        reviewsSlug: null,
        sortTitle: "1492: Conquest of Paradise (1992)",
        title: "1492: Conquest of Paradise",
        year: 1992,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0104257",
        performerNames: ["Jack Nicholson"],
        releaseDate: "1992-12-02",
        reviewsSlug: null,
        sortTitle: "Few Good Men (1992)",
        title: "A Few Good Men",
        year: 1992,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0104114",
        performerNames: ["James Garner"],
        releaseDate: "1992-12-04",
        reviewsSlug: null,
        sortTitle: "Distinguished Gentleman (1992)",
        title: "The Distinguished Gentleman",
        year: 1992,
        writerNames: [],
      },
      {
        directorNames: [],
        collectionNames: [],
        imdbId: "tt0104540",
        performerNames: ["Christopher Lee"],
        releaseDate: "1992-12-23",
        reviewsSlug: null,
        sortTitle: "Cyber Eden (1992)",
        title: "Cyber Eden",
        year: 1992,
        writerNames: [],
      },
    ],
  },
};
