name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      # `--prefer-offline` gives cache priority
      - name: install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: prettier check
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      # `--prefer-offline` gives cache priority
      - name: install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: lint js
        run: yarn lint:js

  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: get gatsby cache
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-buildv4-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-buildv4-

      # `--prefer-offline` gives cache priority
      - name: install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: build
        run: yarn build
        env:
          CI: true

      - name: lint js
        run: yarn type-check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      # `--prefer-offline` gives cache priority
      - name: install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: get gatsby cache
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-buildv4-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-buildv4-

      # `--prefer-offline` gives cache priority
      - name: install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: build
        run: yarn build
        env:
          CI: true

      - name: deploy
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./public"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          timeout-minutes: 5
